from backend.api_v1.base.base_repository import BaseRepository
from backend.api_v1.department_type_parental_links.department_type_parental_link_model import DepartmentTypeParentalLink

class DepartmentTypeParentalLinkRepository(BaseRepository):
    model = DepartmentTypeParentalLink