networks:
  talent:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: talent
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d talent"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      talent:
        ipv4_address: 172.24.0.9

  redis:
    image: redis:5
    volumes:
      - redis_data:/data
    networks:
      talent:
        ipv4_address: 172.24.0.5

  backend:
      &backend
      build:
        context: ./
        dockerfile: ./backend/Dockerfile
        args:
          APP_HTTP_PROXY: ${APP_HTTP_PROXY}
      extra_hosts:
        - ${APP_EXTRA_HOST_LNVUAHQ}
        - ${APP_EXTRA_HOST_LNVDC}
      env_file:
        - stack.env
      environment:
        - NO_PROXY=${APP_NO_PROXY}
      volumes:
        - .env:/app/.env
#        - .env:/app/backend/.env
      depends_on:
        postgres:
          condition: service_healthy
        migrate:
          condition: service_completed_successfully
        redis:
          condition: service_started
      networks:
        talent:
          ipv4_address: 172.24.0.2
      ports:
        - "${APP_PORT}:${APP_CONFIG__RUN__PORT}"

  migrate:
    <<: *backend
    entrypoint: ["poetry", "run", "alembic", "-c", "alembic.ini", "upgrade", "head"]
    command: []
    restart: "no"
    extra_hosts: []
    working_dir: /app/backend
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
      args:
        APP_HTTP_PROXY: ${APP_HTTP_PROXY}
        APP_HTTPS_PROXY: ${APP_HTTPS_PROXY}
        APP_MODE: ${APP_MODE}
      extra_hosts:
        - ${APP_EXTRA_HOST_PROXY}
    env_file:
      - stack.env
    environment:
      - NO_PROXY=${APP_NO_PROXY}
      - VITE_BACKEND_API_URL=http://${APP_VITE_BACKEND_API_URL}:${APP_CONFIG__RUN__PORT}
    networks:
      talent:
        ipv4_address: 172.24.0.3

  nginx:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
    networks:
      talent:
        ipv4_address: 172.24.0.4

volumes:
  redis_data:
  postgres_data: