"""competence summary tables

Revision ID: 734db0819941
Revises: dad9f48f41b7
Create Date: 2026-07-22 13:17:27.491287

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "734db0819941"
down_revision: Union[str, Sequence[str], None] = "dad9f48f41b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competence_summary_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column(
            "description",
            sa.String(length=256),
            server_default="",
            nullable=False,
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_competence_summary_types")
        ),
        sa.UniqueConstraint(
            "key", name=op.f("uq_competence_summary_types_key")
        )
    )
    op.create_table(
        "review_summary_competences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("review_session_employee_id", sa.Integer(), nullable=False),
        sa.Column("competence_summary_type_id", sa.Integer(), nullable=False),
        sa.Column("dimension_id", sa.Integer(), nullable=False),
        sa.Column(
            "sort_order", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competence_summary_type_id"],
            ["competence_summary_types.id"],
            name=op.f(
                "fk_review_summary_competences_competence_summary_type_id_competence_summary_types"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["dimension_id"],
            ["review_dimensions.id"],
            name=op.f(
                "fk_review_summary_competences_dimension_id_review_dimensions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["review_session_employee_id"],
            ["review_session_employees.id"],
            name=op.f(
                "fk_review_summary_competences_review_session_employee_id_review_session_employees"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_summary_competences")
        ),
        sa.UniqueConstraint(
            "review_session_employee_id",
            "competence_summary_type_id",
            "dimension_id",
            name="uq_review_summary_competence",
        )
    )
    op.create_index(
        op.f("ix_review_summary_competences_review_session_employee_id"),
        "review_summary_competences",
        ["review_session_employee_id"],
        unique=False,
    )
    op.create_table(
        "review_summary_competence_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("summary_competence_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "sort_order", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["summary_competence_id"],
            ["review_summary_competences.id"],
            name=op.f(
                "fk_review_summary_competence_comments_summary_competence_id_review_summary_competences"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_summary_competence_comments")
        )
    )
    op.create_index(
        op.f("ix_review_summary_competence_comments_summary_competence_id"),
        "review_summary_competence_comments",
        ["summary_competence_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_review_summary_competence_comments_summary_competence_id"),
        table_name="review_summary_competence_comments",
    )
    op.drop_table("review_summary_competence_comments")
    op.drop_index(
        op.f("ix_review_summary_competences_review_session_employee_id"),
        table_name="review_summary_competences",
    )
    op.drop_table("review_summary_competences")
    op.drop_table("competence_summary_types")
    # ### end Alembic commands ###
