"""add review_session_criterions + criteria is_active

Revision ID: f8898b2e45c4
Revises: 098d5b0ecef2
Create Date: 2026-06-25 20:13:08.713656

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8898b2e45c4"
down_revision: Union[str, Sequence[str], None] = "098d5b0ecef2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_session_criterions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("dimension_id", sa.Integer(), nullable=False),
        sa.Column("source_criteria_id", sa.Integer(), nullable=True),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dimension_id"],
            ["review_dimensions.id"],
            name=op.f(
                "fk_review_session_criterions_dimension_id_review_dimensions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["review_sessions.id"],
            name=op.f(
                "fk_review_session_criterions_session_id_review_sessions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["source_criteria_id"],
            ["review_dimension_criterias.id"],
            name=op.f(
                "fk_review_session_criterions_source_criteria_id_review_dimension_criterias"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_session_criterions")
        )
    )
    op.add_column(
        "review_dimension_criterias",
        sa.Column(
            "is_active", sa.Boolean(), server_default="true", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_dimension_criterias", "is_active")
    op.drop_table("review_session_criterions")
    # ### end Alembic commands ###
