"""make key unique for department categories

Revision ID: 30355878249f
Revises: 0c247b48f174
Create Date: 2026-05-21 10:24:32.939282

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30355878249f"
down_revision: Union[str, Sequence[str], None] = "0c247b48f174"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_department_categories_key", "department_categories", ["key"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_department_categories_key", "department_categories", type_="unique"
    )
    # ### end Alembic commands ###
