"""add_visibility_to_app_settings

Revision ID: df6b1794c6eb
Revises: ddcba7c0a2d5
Create Date: 2026-07-09 20:00:53.293142

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "df6b1794c6eb"
down_revision: Union[str, Sequence[str], None] = "ddcba7c0a2d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_setting_user_group_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("app_setting_id", sa.Integer(), nullable=False),
        sa.Column("user_group_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["app_setting_id"],
            ["app_settings.id"],
            name=op.f(
                "fk_app_setting_user_group_links_app_setting_id_app_settings"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["user_groups.id"],
            name=op.f(
                "fk_app_setting_user_group_links_user_group_id_user_groups"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_app_setting_user_group_links")
        ),
        sa.UniqueConstraint(
            "app_setting_id",
            "user_group_id",
            name="idx_uq_app_setting_user_group",
        )
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "visible_to_all_groups",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "visible_to_regular",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_settings", "visible_to_regular")
    op.drop_column("app_settings", "visible_to_all_groups")
    op.drop_table("app_setting_user_group_links")
    # ### end Alembic commands ###
