"""add essence table and links

Revision ID: f9f196882799
Revises: bfeea158952e
Create Date: 2026-05-24 13:17:18.350912

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9f196882799"
down_revision: Union[str, Sequence[str], None] = "bfeea158952e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "essences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_essences")),
        sa.UniqueConstraint("name", name=op.f("uq_essences_name"))
    )
    op.create_table(
        "operation_essence_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation_id", sa.Integer(), nullable=False),
        sa.Column("essence_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["essence_id"],
            ["essences.id"],
            name=op.f("fk_operation_essence_links_essence_id_essences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_operation_essence_links_operation_id_operations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operation_essence_links")),
        sa.UniqueConstraint(
            "operation_id", "essence_id", name="uq_oel_operation_essence"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operation_essence_links")
    op.drop_table("essences")
    # ### end Alembic commands ###
