"""employee_events_tables

Revision ID: 060a3389f2a1
Revises: 7ec50039cf2b
Create Date: 2026-05-15 11:39:13.078309

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "060a3389f2a1"
down_revision: Union[str, Sequence[str], None] = "7ec50039cf2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_event_change_dept_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_event_change_dept_types")),
        sa.UniqueConstraint(
            "code", name=op.f("uq_employee_event_change_dept_types_code")
        ),
    )
    op.create_table(
        "employee_event_direction_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_event_direction_types")),
        sa.UniqueConstraint(
            "code", name=op.f("uq_employee_event_direction_types_code")
        ),
    )
    op.create_table(
        "employee_event_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_event_types")),
        sa.UniqueConstraint("name", name=op.f("uq_employee_event_types_name")),
    )
    op.create_table(
        "employee_event_type_directions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_type_id", sa.Integer(), nullable=False),
        sa.Column("direction_type_id", sa.Integer(), nullable=False),
        sa.Column("is_required", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["direction_type_id"],
            ["employee_event_direction_types.id"],
            name=op.f(
                "fk_employee_event_type_directions_direction_type_id_employee_event_direction_types"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["employee_event_types.id"],
            name=op.f(
                "fk_employee_event_type_directions_event_type_id_employee_event_types"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_event_type_directions")),
        sa.UniqueConstraint(
            "event_type_id",
            "direction_type_id",
            name="uq_event_type_direction",
        ),
    )
    op.create_index(
        op.f("ix_employee_event_type_directions_event_type_id"),
        "employee_event_type_directions",
        ["event_type_id"],
        unique=False,
    )
    op.create_table(
        "employee_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("event_type_id", sa.Integer(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
            name=op.f("fk_employee_events_created_by_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_events_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["employee_event_types.id"],
            name=op.f("fk_employee_events_event_type_id_employee_event_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_events")),
    )
    op.create_index(
        op.f("ix_employee_events_employee_id"),
        "employee_events",
        ["employee_id"],
        unique=False,
    )
    op.create_table(
        "employee_event_changes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("direction_type_id", sa.Integer(), nullable=False),
        sa.Column("prev_job_id", sa.Integer(), nullable=True),
        sa.Column("new_job_id", sa.Integer(), nullable=True),
        sa.Column("prev_status_id", sa.Integer(), nullable=True),
        sa.Column("new_status_id", sa.Integer(), nullable=True),
        sa.Column("prev_department_id", sa.Integer(), nullable=True),
        sa.Column("new_department_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["direction_type_id"],
            ["employee_event_direction_types.id"],
            name=op.f(
                "fk_employee_event_changes_direction_type_id_employee_event_direction_types"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["employee_events.id"],
            name=op.f("fk_employee_event_changes_event_id_employee_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["new_department_id"],
            ["departments.id"],
            name=op.f("fk_employee_event_changes_new_department_id_departments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["new_job_id"],
            ["jobs.id"],
            name=op.f("fk_employee_event_changes_new_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["new_status_id"],
            ["employee_statuses.id"],
            name=op.f("fk_employee_event_changes_new_status_id_employee_statuses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["prev_department_id"],
            ["departments.id"],
            name=op.f("fk_employee_event_changes_prev_department_id_departments"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["prev_job_id"],
            ["jobs.id"],
            name=op.f("fk_employee_event_changes_prev_job_id_jobs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["prev_status_id"],
            ["employee_statuses.id"],
            name=op.f("fk_employee_event_changes_prev_status_id_employee_statuses"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_event_changes")),
    )
    op.create_index(
        op.f("ix_employee_event_changes_event_id"),
        "employee_event_changes",
        ["event_id"],
        unique=False,
    )
    op.create_table(
        "employee_event_change_departments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_change_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("change_dept_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["change_dept_type_id"],
            ["employee_event_change_dept_types.id"],
            name=op.f(
                "fk_employee_event_change_departments_change_dept_type_id_employee_event_change_dept_types"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_employee_event_change_departments_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["event_change_id"],
            ["employee_event_changes.id"],
            name=op.f(
                "fk_employee_event_change_departments_event_change_id_employee_event_changes"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_employee_event_change_departments")
        ),
        sa.UniqueConstraint(
            "event_change_id",
            "department_id",
            "change_dept_type_id",
            name="uq_event_change_department",
        ),
    )
    op.create_index(
        op.f("ix_employee_event_change_departments_event_change_id"),
        "employee_event_change_departments",
        ["event_change_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_employee_event_change_departments_event_change_id"),
        table_name="employee_event_change_departments",
    )
    op.drop_table("employee_event_change_departments")
    op.drop_index(
        op.f("ix_employee_event_changes_event_id"),
        table_name="employee_event_changes",
    )
    op.drop_table("employee_event_changes")
    op.drop_index(op.f("ix_employee_events_employee_id"), table_name="employee_events")
    op.drop_table("employee_events")
    op.drop_index(
        op.f("ix_employee_event_type_directions_event_type_id"),
        table_name="employee_event_type_directions",
    )
    op.drop_table("employee_event_type_directions")
    op.drop_table("employee_event_types")
    op.drop_table("employee_event_direction_types")
    op.drop_table("employee_event_change_dept_types")
    # ### end Alembic commands ###
