"""add review_session_statuses and replace review_sessions.status string with FK

Revision ID: b49bb4060be5
Revises: 97c5b23d45d2
Create Date: 2026-06-29 18:53:27.828872

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b49bb4060be5"
down_revision: Union[str, Sequence[str], None] = "97c5b23d45d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_session_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_session_statuses")),
        sa.UniqueConstraint(
            "key", name=op.f("uq_review_session_statuses_key")
        )
    )
    op.add_column(
        "review_sessions", sa.Column("status_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_review_sessions_status_id_review_session_statuses"),
        "review_sessions",
        "review_session_statuses",
        ["status_id"],
        ["id"],
    )
    op.drop_column("review_sessions", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_sessions",
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'pending'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_review_sessions_status_id_review_session_statuses"),
        "review_sessions",
        type_="foreignkey",
    )
    op.drop_column("review_sessions", "status_id")
    op.drop_table("review_session_statuses")
    # ### end Alembic commands ###
