"""add essence_set, operation_essence_set_link and user_group_operation_essence_set_link tables

Revision ID: e5ed5ba88af4
Revises: d20c5522e62c
Create Date: 2026-05-27 10:34:42.865341

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5ed5ba88af4"
down_revision: Union[str, Sequence[str], None] = "d20c5522e62c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "essence_sets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("fingerprint", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_essence_sets"))
    )
    op.create_index(
        op.f("ix_essence_sets_fingerprint"),
        "essence_sets",
        ["fingerprint"],
        unique=True,
    )
    op.create_table(
        "essence_set_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("essence_set_id", sa.Integer(), nullable=False),
        sa.Column("essence_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["essence_id"],
            ["essences.id"],
            name=op.f("fk_essence_set_members_essence_id_essences"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["essence_set_id"],
            ["essence_sets.id"],
            name=op.f("fk_essence_set_members_essence_set_id_essence_sets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_essence_set_members")),
        sa.UniqueConstraint(
            "essence_set_id", "essence_id", name="uq_essence_set_member"
        )
    )
    op.create_table(
        "operation_essence_set_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation_id", sa.Integer(), nullable=False),
        sa.Column("essence_set_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["essence_set_id"],
            ["essence_sets.id"],
            name=op.f(
                "fk_operation_essence_set_links_essence_set_id_essence_sets"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f(
                "fk_operation_essence_set_links_operation_id_operations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_operation_essence_set_links")
        ),
        sa.UniqueConstraint(
            "operation_id",
            "essence_set_id",
            name="uq_oesl_operation_essence_set",
        )
    )
    op.create_table(
        "user_group_operation_essence_set_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_group_id", sa.Integer(), nullable=False),
        sa.Column(
            "operation_essence_set_link_id", sa.Integer(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["operation_essence_set_link_id"],
            ["operation_essence_set_links.id"],
            name=op.f(
                "fk_user_group_operation_essence_set_links_operation_essence_set_link_id_operation_essence_set_links"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["user_groups.id"],
            name=op.f(
                "fk_user_group_operation_essence_set_links_user_group_id_user_groups"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_user_group_operation_essence_set_links")
        ),
        sa.UniqueConstraint(
            "user_group_id",
            "operation_essence_set_link_id",
            name="uq_ugoesl_group_oesl",
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_group_operation_essence_set_links")
    op.drop_table("operation_essence_set_links")
    op.drop_table("essence_set_members")
    op.drop_index(
        op.f("ix_essence_sets_fingerprint"), table_name="essence_sets"
    )
    op.drop_table("essence_sets")
    # ### end Alembic commands ###
