"""add review_session_levels and review_session_level_requirements freeze tables

Revision ID: b3b2c3e4819b
Revises: f8898b2e45c4
Create Date: 2026-06-26 11:22:51.596119

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3b2c3e4819b"
down_revision: Union[str, Sequence[str], None] = "f8898b2e45c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_session_levels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("source_level_id", sa.Integer(), nullable=True),
        sa.Column("name_key", sa.String(length=128), nullable=False),
        sa.Column("description_key", sa.String(length=128), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["review_sessions.id"],
            name=op.f("fk_review_session_levels_session_id_review_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_level_id"],
            ["review_levels.id"],
            name=op.f(
                "fk_review_session_levels_source_level_id_review_levels"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_session_levels"))
    )
    op.create_table(
        "review_session_level_requirements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_level_id", sa.Integer(), nullable=False),
        sa.Column("source_requirement_id", sa.Integer(), nullable=True),
        sa.Column("text_key", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["session_level_id"],
            ["review_session_levels.id"],
            name=op.f(
                "fk_review_session_level_requirements_session_level_id_review_session_levels"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["source_requirement_id"],
            ["review_level_requirements.id"],
            name=op.f(
                "fk_review_session_level_requirements_source_requirement_id_review_level_requirements"
            ),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_session_level_requirements")
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("review_session_level_requirements")
    op.drop_table("review_session_levels")
    # ### end Alembic commands ###
