"""add summary_full_competence_list to review_session_employees

Revision ID: fa96998c4153
Revises: 890afa13d30a
Create Date: 2026-07-05 21:11:53.897681

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa96998c4153"
down_revision: Union[str, Sequence[str], None] = "890afa13d30a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_session_employees",
        sa.Column(
            "summary_full_competence_list",
            sa.Boolean(),
            server_default="false",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_session_employees", "summary_full_competence_list")
    # ### end Alembic commands ###
