"""add review_session_departments table

Revision ID: 61eb426f85dd
Revises: d8d7d18a9cac
Create Date: 2026-06-29 19:48:07.572938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "61eb426f85dd"
down_revision: Union[str, Sequence[str], None] = "d8d7d18a9cac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_session_departments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f(
                "fk_review_session_departments_department_id_departments"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["review_sessions.id"],
            name=op.f(
                "fk_review_session_departments_session_id_review_sessions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_session_departments")
        ),
        sa.UniqueConstraint(
            "session_id", "department_id", name="uq_review_session_department"
        )
    )
    op.create_index(
        op.f("ix_review_session_departments_department_id"),
        "review_session_departments",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_review_session_departments_session_id"),
        "review_session_departments",
        ["session_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_review_session_departments_session_id"),
        table_name="review_session_departments",
    )
    op.drop_index(
        op.f("ix_review_session_departments_department_id"),
        table_name="review_session_departments",
    )
    op.drop_table("review_session_departments")
    # ### end Alembic commands ###
