"""employee_events_status

Revision ID: 831dd487e19a
Revises: 060a3389f2a1
Create Date: 2026-05-15 13:15:31.327881

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "831dd487e19a"
down_revision: Union[str, Sequence[str], None] = "060a3389f2a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_event_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_event_statuses")),
        sa.UniqueConstraint(
            "name", name=op.f("uq_employee_event_statuses_name")
        )
    )
    op.add_column(
        "employee_events", sa.Column("status_id", sa.Integer(), nullable=False)
    )
    op.create_foreign_key(
        op.f("fk_employee_events_status_id_employee_event_statuses"),
        "employee_events",
        "employee_event_statuses",
        ["status_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("employee_events", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee_events",
        sa.Column(
            "status",
            sa.VARCHAR(length=16),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_employee_events_status_id_employee_event_statuses"),
        "employee_events",
        type_="foreignkey",
    )
    op.drop_column("employee_events", "status_id")
    op.drop_table("employee_event_statuses")
    # ### end Alembic commands ###
