"""add status to review_session_employee_levels

Revision ID: f30134f38d94
Revises: fd30ccf1085a
Create Date: 2026-06-13 20:39:24.071381

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f30134f38d94"
down_revision: Union[str, Sequence[str], None] = "fd30ccf1085a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_session_employee_levels",
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="proposed",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_session_employee_levels", "status")
    # ### end Alembic commands ###
