"""add department_id to recruitment_tasks

Revision ID: ed6d9c35f600
Revises: 2fb545f92aa0
Create Date: 2026-07-15 20:47:42.114525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed6d9c35f600"
down_revision: Union[str, Sequence[str], None] = "2fb545f92aa0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recruitment_tasks",
        sa.Column("department_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_recruitment_tasks_department_id_departments"),
        "recruitment_tasks",
        "departments",
        ["department_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_recruitment_tasks_department_id_departments"),
        "recruitment_tasks",
        type_="foreignkey",
    )
    op.drop_column("recruitment_tasks", "department_id")
    # ### end Alembic commands ###
