"""add current_level_id to employees

Revision ID: 6d4d61fc6fec
Revises: abce7c32ede2
Create Date: 2026-06-11 19:18:14.212470

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d4d61fc6fec"
down_revision: Union[str, Sequence[str], None] = "abce7c32ede2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_levels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name_key", sa.String(length=128), nullable=False),
        sa.Column("description_key", sa.String(length=128), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_levels")),
        sa.UniqueConstraint(
            "name_key", name=op.f("uq_review_levels_name_key")
        )
    )
    op.create_table(
        "review_level_requirements",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("level_id", sa.Integer(), nullable=False),
        sa.Column("text_key", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["review_levels.id"],
            name=op.f("fk_review_level_requirements_level_id_review_levels"),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_level_requirements")
        )
    )
    op.create_table(
        "review_session_employee_levels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("review_session_employee_id", sa.Integer(), nullable=False),
        sa.Column("level_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["review_levels.id"],
            name=op.f(
                "fk_review_session_employee_levels_level_id_review_levels"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["review_session_employee_id"],
            ["review_session_employees.id"],
            name=op.f(
                "fk_review_session_employee_levels_review_session_employee_id_review_session_employees"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_session_employee_levels")
        ),
        sa.UniqueConstraint(
            "review_session_employee_id",
            name=op.f(
                "uq_review_session_employee_levels_review_session_employee_id"
            ),
        )
    )
    op.create_table(
        "review_session_employee_level_answers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "review_session_employee_level_id", sa.Integer(), nullable=False
        ),
        sa.Column("requirement_id", sa.Integer(), nullable=False),
        sa.Column("facts", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["requirement_id"],
            ["review_level_requirements.id"],
            name=op.f(
                "fk_review_session_employee_level_answers_requirement_id_review_level_requirements"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["review_session_employee_level_id"],
            ["review_session_employee_levels.id"],
            name=op.f(
                "fk_review_session_employee_level_answers_review_session_employee_level_id_review_session_employee_levels"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_session_employee_level_answers")
        )
    )
    op.drop_constraint(
        op.f("uq_employee_department"), "employee_departments", type_="unique"
    )
    op.create_unique_constraint(
        "uq_employee_department",
        "employee_departments",
        ["employee_id", "department_id"],
    )
    op.add_column(
        "employees", sa.Column("current_level_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_employees_current_level_id_review_levels"),
        "employees",
        "review_levels",
        ["current_level_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_employees_current_level_id_review_levels"),
        "employees",
        type_="foreignkey",
    )
    op.drop_column("employees", "current_level_id")
    op.drop_constraint(
        "uq_employee_department", "employee_departments", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_employee_department"),
        "employee_departments",
        ["employee_id", "department_id", "is_main"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_table("review_session_employee_level_answers")
    op.drop_table("review_session_employee_levels")
    op.drop_table("review_level_requirements")
    op.drop_table("review_levels")
    # ### end Alembic commands ###
