"""add is_main to employee_department unique constraint

Revision ID: d20c5522e62c
Revises: 1e0eab0c289c
Create Date: 2026-05-25 09:53:58.251628

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d20c5522e62c"
down_revision: Union[str, Sequence[str], None] = "1e0eab0c289c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_employee_department"), "employee_departments", type_="unique"
    )
    op.create_unique_constraint(
        "uq_employee_department",
        "employee_departments",
        ["employee_id", "department_id", "is_main"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_employee_department", "employee_departments", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_employee_department"),
        "employee_departments",
        ["employee_id", "department_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
