"""employee related tables

Revision ID: bc8d66e6e979
Revises: dd523421ce99
Create Date: 2026-05-08 20:02:39.019211

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc8d66e6e979"
down_revision: Union[str, Sequence[str], None] = "dd523421ce99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_statuses")),
        sa.UniqueConstraint("name", name=op.f("uq_employee_statuses_name")),
    )
    op.create_table(
        "jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
        sa.UniqueConstraint("name", name=op.f("uq_jobs_name")),
    )

    op.create_table(
        "operations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_operations")),
        sa.UniqueConstraint("name", name=op.f("uq_operations_name")),
    )
    op.create_table(
        "user_group_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_group_types")),
        sa.UniqueConstraint("name", name=op.f("uq_user_group_types_name")),
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("lang_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["jobs.id"], name=op.f("fk_employees_job_id_jobs")
        ),
        sa.ForeignKeyConstraint(
            ["lang_id"], ["langs.id"], name=op.f("fk_employees_lang_id_langs")
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["employee_statuses.id"],
            name=op.f("fk_employees_status_id_employee_statuses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employees")),
        sa.UniqueConstraint("code", name=op.f("uq_employees_code")),
        sa.UniqueConstraint("email", name=op.f("uq_employees_email")),
    )
    op.create_table(
        "user_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_protected", sa.Boolean(), nullable=False),
        sa.Column("user_group_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_group_type_id"],
            ["user_group_types.id"],
            name=op.f("fk_user_groups_user_group_type_id_user_group_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_groups")),
    )
    op.create_table(
        "employee_user_group_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("user_group_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_user_group_links_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["user_groups.id"],
            name=op.f(
                "fk_employee_user_group_links_user_group_id_user_groups"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_employee_user_group_links")
        ),
        sa.UniqueConstraint(
            "employee_id", "user_group_id", name="idx_uq_user_user_group"
        ),
    )
    op.create_table(
        "job_user_group_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("user_group_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_user_group_links_job_id_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["user_groups.id"],
            name=op.f("fk_job_user_group_links_user_group_id_user_groups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_user_group_links")),
        sa.UniqueConstraint(
            "job_id", "user_group_id", name="idx_uq_job_user_group"
        ),
    )
    op.create_table(
        "operation_user_group_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operation_id", sa.Integer(), nullable=False),
        sa.Column("user_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_id"],
            ["operations.id"],
            name=op.f("fk_operation_user_group_links_operation_id_operations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["user_groups.id"],
            name=op.f(
                "fk_operation_user_group_links_user_group_id_user_groups"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_operation_user_group_links")
        ),
        sa.UniqueConstraint(
            "operation_id", "user_group_id", name="idx_uq_operation_user_group"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operation_user_group_links")
    op.drop_table("job_user_group_links")
    op.drop_table("employee_user_group_links")
    op.drop_table("user_groups")
    op.drop_table("employees")
    op.drop_table("user_group_types")
    op.drop_table("operations")
    op.drop_table("jobs")
    op.drop_table("employee_statuses")
    # ### end Alembic commands ###
