"""widen uq_employee_department to include is_main

Revision ID: 098d5b0ecef2
Revises: 7047781ecb6f
Create Date: 2026-06-24 21:39:17.191672

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "098d5b0ecef2"
down_revision: Union[str, Sequence[str], None] = "7047781ecb6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_employee_department"), "employee_departments", type_="unique"
    )
    op.create_unique_constraint(
        "uq_employee_department",
        "employee_departments",
        ["employee_id", "department_id", "is_main"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_employee_department", "employee_departments", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq_employee_department"),
        "employee_departments",
        ["employee_id", "department_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
