"""drop development plan from review session employees

Revision ID: dad9f48f41b7
Revises: dafe3b95ca2f
Create Date: 2026-07-22 11:40:26.709988

IRREVERSIBLE DATA LOSS. The development plan moved to the employee-scoped
`employee_missions` tables (created in 5481033843c6). The data move that fills
them ran as a separate one-shot script BETWEEN that revision and this one --
which is exactly why the drop was never folded into the create.

Run this ONLY on a database where the missions tables are already populated.
The check is one query; the plans it protects cannot be recovered:

    SELECT count(*) FROM review_session_employees
    WHERE development_plan IS NOT NULL AND btrim(development_plan) NOT IN ('', '[]');
    SELECT count(DISTINCT employee_id) FROM employee_missions;

`downgrade()` re-adds the column EMPTY -- it restores the shape, never the
content. A `pg_dump -t review_session_employees` taken beforehand is the only
real rollback.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dad9f48f41b7"
down_revision: Union[str, Sequence[str], None] = "dafe3b95ca2f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_session_employees", "development_plan")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Re-creates the column EMPTY. The plans are not restored -- see the module
    docstring.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_session_employees",
        sa.Column("development_plan", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
