"""person name and employee person_id not null

Revision ID: 4023937c38c0
Revises: b22b673caf3f
Create Date: 2026-07-07 23:59:50.193180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4023937c38c0"
down_revision: Union[str, Sequence[str], None] = "b22b673caf3f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees", "person_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "persons",
        "first_name",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.alter_column(
        "persons",
        "last_name",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "persons",
        "last_name",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    op.alter_column(
        "persons",
        "first_name",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    op.alter_column(
        "employees", "person_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
