"""person_events: types, statuses, events, changes

Revision ID: 55496e4b3bd5
Revises: 24a873b0337f
Create Date: 2026-07-30 22:02:51.355434

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55496e4b3bd5"
down_revision: Union[str, Sequence[str], None] = "24a873b0337f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "person_event_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_event_statuses")),
        sa.UniqueConstraint(
            "name", name=op.f("uq_person_event_statuses_name")
        )
    )
    op.create_table(
        "person_event_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_event_types")),
        sa.UniqueConstraint("key", name=op.f("uq_person_event_types_key")),
        sa.UniqueConstraint("name", name=op.f("uq_person_event_types_name"))
    )
    op.create_table(
        "person_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("person_id", sa.Integer(), nullable=False),
        sa.Column("event_type_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
            name=op.f("fk_person_events_created_by_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["event_type_id"],
            ["person_event_types.id"],
            name=op.f("fk_person_events_event_type_id_person_event_types"),
        ),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["persons.id"],
            name=op.f("fk_person_events_person_id_persons"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["person_event_statuses.id"],
            name=op.f("fk_person_events_status_id_person_event_statuses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_events"))
    )
    op.create_table(
        "person_event_changes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("field_key", sa.String(length=64), nullable=False),
        sa.Column("prev_value", sa.Text(), nullable=True),
        sa.Column("new_value", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["person_events.id"],
            name=op.f("fk_person_event_changes_event_id_person_events"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_person_event_changes"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("person_event_changes")
    op.drop_table("person_events")
    op.drop_table("person_event_types")
    op.drop_table("person_event_statuses")
    # ### end Alembic commands ###
