"""create msg table and links

Revision ID: dd523421ce99
Revises: d822390f8972
Create Date: 2026-05-07 19:08:16.110447

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dd523421ce99"
down_revision: Union[str, Sequence[str], None] = "d822390f8972"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "msgs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("msg_key_id", sa.Integer(), nullable=False),
        sa.Column("lang_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["lang_id"], ["langs.id"], name=op.f("fk_msgs_lang_id_langs")
        ),
        sa.ForeignKeyConstraint(
            ["msg_key_id"],
            ["msg_keys.id"],
            name=op.f("fk_msgs_msg_key_id_msg_keys"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_msgs")),
        sa.UniqueConstraint("lang_id", "msg_key_id", name="uq_msg_key_lang"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("msgs")
    # ### end Alembic commands ###
