"""add setting_value_types and app_settings tables

Revision ID: fd0f688707cd
Revises: 16897a46f19d
Create Date: 2026-06-22 19:48:04.656389

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd0f688707cd"
down_revision: Union[str, Sequence[str], None] = "16897a46f19d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "setting_value_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_setting_value_types")),
        sa.UniqueConstraint("key", name=op.f("uq_setting_value_types_key"))
    )
    op.create_table(
        "app_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("value_type_id", sa.Integer(), nullable=False),
        sa.Column("label_key", sa.String(length=64), nullable=True),
        sa.Column("description_key", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
            name=op.f("fk_app_settings_created_by_employees"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["value_type_id"],
            ["setting_value_types.id"],
            name=op.f("fk_app_settings_value_type_id_setting_value_types"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_settings")),
        sa.UniqueConstraint("key", name=op.f("uq_app_settings_key"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("app_settings")
    op.drop_table("setting_value_types")
    # ### end Alembic commands ###
