"""add department_type_job_link table and relationhip

Revision ID: 16fa6da945bc
Revises: 307351b26ddb
Create Date: 2026-05-19 14:44:25.913929

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16fa6da945bc"
down_revision: Union[str, Sequence[str], None] = "307351b26ddb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "department_type_job_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("department_type_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_type_id"],
            ["department_types.id"],
            name=op.f(
                "fk_department_type_job_links_department_type_id_department_types"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_department_type_job_links_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department_type_job_links")),
        sa.UniqueConstraint(
            "department_type_id", "job_id", name="idx_uq_department_type_job"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("department_type_job_links")
    # ### end Alembic commands ###
