"""add parent_id self-fk to app_settings

Revision ID: b7f4f891e780
Revises: 61eb426f85dd
Create Date: 2026-06-30 13:57:57.654188

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b7f4f891e780"
down_revision: Union[str, Sequence[str], None] = "61eb426f85dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_settings", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_app_settings_parent_id_app_settings"),
        "app_settings",
        "app_settings",
        ["parent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_app_settings_parent_id_app_settings"),
        "app_settings",
        type_="foreignkey",
    )
    op.drop_column("app_settings", "parent_id")
    # ### end Alembic commands ###
