"""add UserGroupOperationEssenceLink table

Revision ID: afb6e84ea22b
Revises: f9f196882799
Create Date: 2026-05-24 13:31:30.207952

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "afb6e84ea22b"
down_revision: Union[str, Sequence[str], None] = "f9f196882799"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_group_operation_essence_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_group_id", sa.Integer(), nullable=False),
        sa.Column("operation_essence_link_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operation_essence_link_id"],
            ["operation_essence_links.id"],
            name=op.f(
                "fk_user_group_operation_essence_links_operation_essence_link_id_operation_essence_links"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_group_id"],
            ["user_groups.id"],
            name=op.f(
                "fk_user_group_operation_essence_links_user_group_id_user_groups"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_user_group_operation_essence_links")
        ),
        sa.UniqueConstraint(
            "user_group_id",
            "operation_essence_link_id",
            name="uq_ugoel_group_oel",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_group_operation_essence_links")
    # ### end Alembic commands ###
