"""review_dimension color and sort_order

Revision ID: 16897a46f19d
Revises: e6649c6b476c
Create Date: 2026-06-20 15:39:35.257845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "16897a46f19d"
down_revision: Union[str, Sequence[str], None] = "e6649c6b476c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Seed colors = the values the frontend used before color lived in the DB
# (frontend/src/components/people-review/evaluation/evaluationHelpers.ts).
_SEED_COLORS = {
    "TRANSFORMATION": "#1565C0",
    "ETHICS": "#2E7D32",
    "MOBILIZATION": "#E65100",
    "PEOPLE_PLANET": "#0097A7",
    "OPENNESS": "#D32F2F",
    "CUSTOMER_RESULTS": "#AD1457",
}


def upgrade() -> None:
    """Upgrade schema."""
    # Add with a temporary server_default so existing rows get a valid value,
    # then backfill real colors/order and drop the default (new rows get their
    # value from the model-side default instead).
    op.add_column(
        "review_dimensions",
        sa.Column(
            "color",
            sa.String(length=7),
            nullable=False,
            server_default="#1565C0",
        ),
    )
    op.add_column(
        "review_dimensions",
        sa.Column(
            "sort_order",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )

    # Backfill the known dimension colors by key.
    for key, color in _SEED_COLORS.items():
        op.execute(
            sa.text(
                "UPDATE review_dimensions SET color = :color WHERE key = :key"
            ).bindparams(color=color, key=key)
        )

    # Backfill display order in 10s (10, 20, 30...) by current id order.
    op.execute(
        """
        WITH ordered AS (
            SELECT id, ROW_NUMBER() OVER (ORDER BY id) AS rn
            FROM review_dimensions
        )
        UPDATE review_dimensions d
        SET sort_order = ordered.rn * 10
        FROM ordered
        WHERE d.id = ordered.id
        """
    )

    # Drop the temporary defaults; the application supplies values going forward.
    op.alter_column("review_dimensions", "color", server_default=None)
    op.alter_column("review_dimensions", "sort_order", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_dimensions", "sort_order")
    op.drop_column("review_dimensions", "color")
    # ### end Alembic commands ###
