"""add regions, department_region_links, hrm_scopes, audit change_session/change_log + talent_audit.talent_plus

Revision ID: 7047781ecb6f
Revises: fd0f688707cd
Create Date: 2026-06-24 16:06:21.804383

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7047781ecb6f"
down_revision: Union[str, Sequence[str], None] = "fd0f688707cd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "sort_order", sa.Integer(), server_default="10", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
        sa.UniqueConstraint("key", name="idx_uq_region_key"),
        sa.UniqueConstraint("name", name="idx_uq_region_name")
    )
    op.create_index(
        op.f("ix_regions_sort_order"), "regions", ["sort_order"], unique=False
    )
    op.create_table(
        "change_session",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("triggered_by_user_id", sa.Integer(), nullable=True),
        sa.Column("task_name", sa.String(length=128), nullable=True),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.String(length=16),
            server_default="running",
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "summary", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_change_session_employee_id_employees"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["triggered_by_user_id"],
            ["employees.id"],
            name=op.f("fk_change_session_triggered_by_user_id_employees"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_session"))
    )
    op.create_index(
        op.f("ix_change_session_employee_id"),
        "change_session",
        ["employee_id"],
        unique=False,
    )
    op.create_table(
        "department_region_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_department_region_links_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
            name=op.f("fk_department_region_links_region_id_regions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department_region_links")),
        sa.UniqueConstraint(
            "department_id", name="idx_uq_department_region_department"
        )
    )
    op.create_table(
        "change_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("change_session_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("essence_key", sa.String(length=64), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column(
            "changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("employee_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_session_id"],
            ["change_session.id"],
            name=op.f("fk_change_log_change_session_id_change_session"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_change_log_employee_id_employees"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["change_log.id"],
            name=op.f("fk_change_log_parent_id_change_log"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_log"))
    )
    op.create_index(
        op.f("ix_change_log_employee_id"),
        "change_log",
        ["employee_id"],
        unique=False,
    )
    op.create_table(
        "hrm_scopes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_user_group_link_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_hrm_scopes_department_id_departments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_hrm_scopes_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_user_group_link_id"],
            ["employee_user_group_links.id"],
            name=op.f(
                "fk_hrm_scopes_employee_user_group_link_id_employee_user_group_links"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hrm_scopes"))
    )
    op.create_index(
        "ix_hrm_scopes_department_id",
        "hrm_scopes",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        "ix_hrm_scopes_employee_id",
        "hrm_scopes",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        "ix_hrm_scopes_link_id",
        "hrm_scopes",
        ["employee_user_group_link_id"],
        unique=False,
    )
    op.create_index(
        "ix_hrm_scopes_window",
        "hrm_scopes",
        ["start_date", "end_date"],
        unique=False,
    )
    op.add_column(
        "talent_audit",
        sa.Column(
            "talent_plus", sa.Boolean(), server_default="false", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("talent_audit", "talent_plus")
    op.drop_index("ix_hrm_scopes_window", table_name="hrm_scopes")
    op.drop_index("ix_hrm_scopes_link_id", table_name="hrm_scopes")
    op.drop_index("ix_hrm_scopes_employee_id", table_name="hrm_scopes")
    op.drop_index("ix_hrm_scopes_department_id", table_name="hrm_scopes")
    op.drop_table("hrm_scopes")
    op.drop_index(op.f("ix_change_log_employee_id"), table_name="change_log")
    op.drop_table("change_log")
    op.drop_table("department_region_links")
    op.drop_index(
        op.f("ix_change_session_employee_id"), table_name="change_session"
    )
    op.drop_table("change_session")
    op.drop_index(op.f("ix_regions_sort_order"), table_name="regions")
    op.drop_table("regions")
    # ### end Alembic commands ###
