"""rename recruitment tables to one recruitment_ stem

Pure rename — NO data is moved, created or destroyed. Every row that existed before
this revision exists after it, in the same table, with the same id.

Hand-written on purpose (the standing exception to the autogenerate rule): autogenerate
cannot recognise a rename. It would emit drop_table + create_table and silently destroy
every candidate, application, interview and status-history row.

Why the rename
--------------
The module had grown six unrelated name stems for one module, and two of its tables
claimed globally ambiguous nouns:

  * `pipeline_statuses` — whose pipeline? It is the application pipeline, and the sibling
    lookup is already `recruitment_task_statuses`.
  * `application_status_history` — whose application? Also the only singular table in the
    module.
  * `interviews` — `talent_audit_interview` already exists, so the bare noun was taken.

`candidate_*` is folded in so the whole module sorts as one block. `job_requirement_*`
deliberately keeps its own stem: `jobs` owns those rows, recruitment only reads them.

Constraint and index names
--------------------------
Postgres keeps the OLD constraint names through a table rename, so leaving them would
make every future autogenerate show drift against the metadata naming convention. Two
traps make these impossible to write by hand:

  1. The convention in `backend/config/database.py` is
     `fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s`, which embeds both
     table names and easily passes 63 bytes.
  2. Past 63 bytes SQLAlchemy does not clip — it renders `name[:55] + "_" + md5(name)[-4:]`.
     That hashed form is what is actually in the database, so a migration spelling out
     the untruncated name fails.

Both sides below were therefore GENERATED, not typed:
`python scripts/naming/gen_rename_names.py`.

Access control
--------------
`essences.name` must match `EssenceName` in `backend/utils/enums.py` — `has_access_set`
resolves a guard by that string, and the grants hang off `operation_essence_links.essence_id`.
The six renamed essences are therefore UPDATEd in place, in this same revision, so the
rename is atomic with the code that depends on it. They are never delete-and-inserted:
a new row would carry no grants and every recruitment endpoint would 403.

Still to do OUTSIDE this revision (not schema): the essence label msg_keys, which are
the camelCase of the essence name (`candidate` -> `candidateSource` -> …). New keys go in
via /add-translation.

Revision ID: c7e1a94f5b30
Revises: d42987ead6ad
Create Date: 2026-07-30 15:20:11.402887

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision: str = "c7e1a94f5b30"
down_revision: Union[str, Sequence[str], None] = "d42987ead6ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# (old, new)
TABLES = [
    ("candidates", "recruitment_candidates"),
    ("candidate_sources", "recruitment_candidate_sources"),
    ("candidate_phones", "recruitment_candidate_phones"),
    ("candidate_notes", "recruitment_candidate_notes"),
    ("candidate_applications", "recruitment_applications"),
    ("pipeline_statuses", "recruitment_application_statuses"),
    ("application_status_history", "recruitment_application_status_changes"),
    ("interviews", "recruitment_interviews"),
    ("interview_interviewers", "recruitment_interview_interviewers"),
    ("interview_feedbacks", "recruitment_interview_feedbacks"),
]

# (table, old_column, new_column) — applied AFTER the table renames, so the table names
# here are already the new ones.
#   * FK columns take the singular of the table they point at, minus the stem they share
#     with the owning table.
#   * the actor column is `created_by` everywhere; `author_id` / `changed_by` were three
#     names for one concept.
COLUMNS = [
    ("recruitment_tasks", "requirement_group_id", "job_requirement_group_id"),
    ("recruitment_candidates", "source_id", "candidate_source_id"),
    ("recruitment_candidate_notes", "author_id", "created_by"),
    ("recruitment_interview_feedbacks", "author_id", "created_by"),
    ("recruitment_application_status_changes", "changed_by", "created_by"),
    ("recruitment_application_status_changes", "changed_at", "created_at"),
]

# (table, old, new) — primary keys, unique and foreign key constraints. Postgres treats
# a unique/primary constraint and its backing index as one object, so renaming the
# constraint renames that index with it.
# Generated by scripts/naming/gen_rename_names.py — do not hand-edit.
CONSTRAINTS = [
    ("recruitment_candidates", "pk_candidates", "pk_recruitment_candidates"),
    (
        "recruitment_candidates",
        "fk_candidates_created_by_employees",
        "fk_recruitment_candidates_created_by_employees",
    ),
    (
        "recruitment_candidates",
        "fk_candidates_source_id_candidate_sources",
        "fk_recruitment_candidates_candidate_source_id_recruitme_bb3d",
    ),
    (
        "recruitment_candidates",
        "uq_candidates_email",
        "uq_recruitment_candidates_email",
    ),
    (
        "recruitment_candidate_sources",
        "pk_candidate_sources",
        "pk_recruitment_candidate_sources",
    ),
    (
        "recruitment_candidate_sources",
        "uq_candidate_sources_key",
        "uq_recruitment_candidate_sources_key",
    ),
    (
        "recruitment_candidate_phones",
        "pk_candidate_phones",
        "pk_recruitment_candidate_phones",
    ),
    (
        "recruitment_candidate_phones",
        "fk_candidate_phones_candidate_id_candidates",
        "fk_recruitment_candidate_phones_candidate_id_recruitmen_7f83",
    ),
    (
        "recruitment_candidate_notes",
        "pk_candidate_notes",
        "pk_recruitment_candidate_notes",
    ),
    (
        "recruitment_candidate_notes",
        "fk_candidate_notes_author_id_employees",
        "fk_recruitment_candidate_notes_created_by_employees",
    ),
    (
        "recruitment_candidate_notes",
        "fk_candidate_notes_candidate_id_candidates",
        "fk_recruitment_candidate_notes_candidate_id_recruitment_af6d",
    ),
    (
        "recruitment_applications",
        "pk_candidate_applications",
        "pk_recruitment_applications",
    ),
    (
        "recruitment_applications",
        "fk_candidate_applications_candidate_id_candidates",
        "fk_recruitment_applications_candidate_id_recruitment_candidates",
    ),
    (
        "recruitment_applications",
        "fk_candidate_applications_created_by_employees",
        "fk_recruitment_applications_created_by_employees",
    ),
    (
        "recruitment_applications",
        "fk_candidate_applications_recruitment_task_id_recruitment_tasks",
        "fk_recruitment_applications_recruitment_task_id_recruit_d93b",
    ),
    (
        "recruitment_applications",
        "fk_candidate_applications_status_id_pipeline_statuses",
        "fk_recruitment_applications_status_id_recruitment_appli_4ae0",
    ),
    (
        "recruitment_applications",
        "uq_candidate_application_candidate_task",
        "uq_recruitment_application_candidate_task",
    ),
    (
        "recruitment_application_statuses",
        "pk_pipeline_statuses",
        "pk_recruitment_application_statuses",
    ),
    (
        "recruitment_application_statuses",
        "uq_pipeline_statuses_name",
        "uq_recruitment_application_statuses_name",
    ),
    (
        "recruitment_application_status_changes",
        "pk_application_status_history",
        "pk_recruitment_application_status_changes",
    ),
    (
        "recruitment_application_status_changes",
        "fk_application_status_history_application_id_candidate__e0ac",
        "fk_recruitment_application_status_changes_application_i_550f",
    ),
    (
        "recruitment_application_status_changes",
        "fk_application_status_history_changed_by_employees",
        "fk_recruitment_application_status_changes_created_by_employees",
    ),
    (
        "recruitment_application_status_changes",
        "fk_application_status_history_status_id_pipeline_statuses",
        "fk_recruitment_application_status_changes_status_id_rec_3939",
    ),
    ("recruitment_interviews", "pk_interviews", "pk_recruitment_interviews"),
    (
        "recruitment_interviews",
        "fk_interviews_application_id_candidate_applications",
        "fk_recruitment_interviews_application_id_recruitment_ap_9e35",
    ),
    (
        "recruitment_interviews",
        "fk_interviews_created_by_employees",
        "fk_recruitment_interviews_created_by_employees",
    ),
    (
        "recruitment_interview_interviewers",
        "pk_interview_interviewers",
        "pk_recruitment_interview_interviewers",
    ),
    (
        "recruitment_interview_interviewers",
        "fk_interview_interviewers_employee_id_employees",
        "fk_recruitment_interview_interviewers_employee_id_employees",
    ),
    (
        "recruitment_interview_interviewers",
        "fk_interview_interviewers_interview_id_interviews",
        "fk_recruitment_interview_interviewers_interview_id_recr_d278",
    ),
    (
        "recruitment_interview_interviewers",
        "uq_interview_interviewer",
        "uq_recruitment_interview_interviewer",
    ),
    (
        "recruitment_interview_feedbacks",
        "pk_interview_feedbacks",
        "pk_recruitment_interview_feedbacks",
    ),
    (
        "recruitment_interview_feedbacks",
        "fk_interview_feedbacks_author_id_employees",
        "fk_recruitment_interview_feedbacks_created_by_employees",
    ),
    (
        "recruitment_interview_feedbacks",
        "fk_interview_feedbacks_interview_id_interviews",
        "fk_recruitment_interview_feedbacks_interview_id_recruit_913e",
    ),
    (
        "recruitment_tasks",
        "fk_recruitment_tasks_requirement_group_id_job_requireme_c91b",
        "fk_recruitment_tasks_job_requirement_group_id_job_requi_b017",
    ),
]

# (old, new) — `essences.name`, which access guards resolve by string.
ESSENCES = [
    ("candidate", "recruitment_candidate"),
    ("candidate_source", "recruitment_candidate_source"),
    ("candidate_application", "recruitment_application"),
    ("pipeline_status", "recruitment_application_status"),
    ("interview", "recruitment_interview"),
    ("interview_feedback", "recruitment_interview_feedback"),
]


def _rename_essences(pairs: list[tuple[str, str]]) -> None:
    """UPDATE in place so the essence keeps its id, and therefore its grants."""
    for old, new in pairs:
        op.get_bind().execute(
            text("UPDATE essences SET name = :new WHERE name = :old"),
            {"new": new, "old": old},
        )


def upgrade() -> None:
    """Upgrade schema."""
    for old, new in TABLES:
        op.rename_table(old, new)
    for table, old, new in COLUMNS:
        op.alter_column(table, old, new_column_name=new)
    for table, old, new in CONSTRAINTS:
        op.execute(f'ALTER TABLE {table} RENAME CONSTRAINT "{old}" TO "{new}"')
    _rename_essences(ESSENCES)


def downgrade() -> None:
    """Downgrade schema — the exact inverse, equally lossless."""
    _rename_essences([(new, old) for old, new in ESSENCES])
    for table, old, new in CONSTRAINTS:
        op.execute(f'ALTER TABLE {table} RENAME CONSTRAINT "{new}" TO "{old}"')
    for table, old, new in COLUMNS:
        op.alter_column(table, new, new_column_name=old)
    for old, new in reversed(TABLES):
        op.rename_table(new, old)
