"""add job_process_role_links

Revision ID: 97c5b23d45d2
Revises: 39fdc03387dd
Create Date: 2026-06-26 21:13:38.280643

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "97c5b23d45d2"
down_revision: Union[str, Sequence[str], None] = "39fdc03387dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_process_role_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("process_role_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_process_role_links_job_id_jobs"),
        ),
        sa.ForeignKeyConstraint(
            ["process_role_id"],
            ["process_roles.id"],
            name=op.f(
                "fk_job_process_role_links_process_role_id_process_roles"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_process_role_links")),
        sa.UniqueConstraint(
            "job_id", "process_role_id", name="uq_job_process_role"
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_process_role_links")
    # ### end Alembic commands ###
