"""add key to job group

Revision ID: 0407ea77bce1
Revises: 64586f81cbd1
Create Date: 2026-05-23 19:22:25.046947

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0407ea77bce1"
down_revision: Union[str, Sequence[str], None] = "64586f81cbd1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("job_groups", sa.Column("key", sa.String(length=64), nullable=True))
    op.create_unique_constraint(op.f("uq_job_groups_key"), "job_groups", ["key"])
    op.drop_column("job_groups", "is_protected")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "job_groups",
        sa.Column("is_protected", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("uq_job_groups_key"), "job_groups", type_="unique")
    op.drop_column("job_groups", "key")
    # ### end Alembic commands ###
