"""add job_responsibility_category_link

Revision ID: 1e0eab0c289c
Revises: afb6e84ea22b
Create Date: 2026-05-24 21:32:31.538182

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e0eab0c289c"
down_revision: Union[str, Sequence[str], None] = "afb6e84ea22b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_responsibility_category_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("department_category_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_category_id"],
            ["department_categories.id"],
            name=op.f(
                "fk_job_responsibility_category_links_department_category_id_department_categories"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_responsibility_category_links_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_job_responsibility_category_links")
        ),
        sa.UniqueConstraint(
            "job_id",
            "department_category_id",
            name="idx_uq_job_responsibility_category",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_responsibility_category_links")
    # ### end Alembic commands ###
