"""add employee fact types, facts and evaluation links

Revision ID: 88e434a4005b
Revises: 9976b2934c34
Create Date: 2026-07-29 18:14:13.769591

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88e434a4005b"
down_revision: Union[str, Sequence[str], None] = "9976b2934c34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_fact_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column(
            "description",
            sa.String(length=256),
            server_default="",
            nullable=False,
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_fact_types")),
        sa.UniqueConstraint("key", name=op.f("uq_employee_fact_types_key"))
    )
    op.create_table(
        "employee_facts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("employee_fact_type_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("created_by_id", sa.Integer(), nullable=False),
        sa.Column("updated_by_id", sa.Integer(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["employees.id"],
            name=op.f("fk_employee_facts_created_by_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_fact_type_id"],
            ["employee_fact_types.id"],
            name=op.f(
                "fk_employee_facts_employee_fact_type_id_employee_fact_types"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_facts_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["employees.id"],
            name=op.f("fk_employee_facts_updated_by_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_facts"))
    )
    op.create_index(
        op.f("ix_employee_facts_employee_fact_type_id"),
        "employee_facts",
        ["employee_fact_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_employee_facts_employee_id"),
        "employee_facts",
        ["employee_id"],
        unique=False,
    )
    op.create_table(
        "employee_fact_evaluation_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_fact_id", sa.Integer(), nullable=False),
        sa.Column(
            "review_session_employee_evaluation_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_fact_id"],
            ["employee_facts.id"],
            name=op.f(
                "fk_employee_fact_evaluation_links_employee_fact_id_employee_facts"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["review_session_employee_evaluation_id"],
            ["review_session_employee_evaluations.id"],
            name=op.f(
                "fk_employee_fact_evaluation_links_review_session_employee_evaluation_id_review_session_employee_evaluations"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_employee_fact_evaluation_links")
        ),
        sa.UniqueConstraint(
            "employee_fact_id",
            name=op.f("uq_employee_fact_evaluation_links_employee_fact_id"),
        )
    )
    op.create_index(
        op.f(
            "ix_employee_fact_evaluation_links_review_session_employee_evaluation_id"
        ),
        "employee_fact_evaluation_links",
        ["review_session_employee_evaluation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f(
            "ix_employee_fact_evaluation_links_review_session_employee_evaluation_id"
        ),
        table_name="employee_fact_evaluation_links",
    )
    op.drop_table("employee_fact_evaluation_links")
    op.drop_index(
        op.f("ix_employee_facts_employee_id"), table_name="employee_facts"
    )
    op.drop_index(
        op.f("ix_employee_facts_employee_fact_type_id"),
        table_name="employee_facts",
    )
    op.drop_table("employee_facts")
    op.drop_table("employee_fact_types")
    # ### end Alembic commands ###
