"""drop review_session_employees.competence_summary

The strong / to-develop summary now lives in `review_summary_competences` +
`review_summary_competence_comments` (created in 734db0819941 and populated by
backend/scripts/migrate_competence_summaries.py, run between the two revisions).

WARNING: `downgrade()` recreates the column EMPTY. The JSON content cannot be
restored from here — it only ever existed in this column, and the reverse
conversion (rows back to a blob) is not implemented. Take a
`pg_dump -t review_session_employees` before applying if the data still matters.

Revision ID: c30e360e7d76
Revises: 734db0819941
Create Date: 2026-07-22 13:37:11.440505

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c30e360e7d76"
down_revision: Union[str, Sequence[str], None] = "734db0819941"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_session_employees", "competence_summary")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "review_session_employees",
        sa.Column(
            "competence_summary", sa.TEXT(), autoincrement=False, nullable=True
        ),
    )
    # ### end Alembic commands ###
