"""employee jobid nullable

Revision ID: bfeea158952e
Revises: 0407ea77bce1
Create Date: 2026-05-24 01:57:34.772832

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bfeea158952e"
down_revision: Union[str, Sequence[str], None] = "0407ea77bce1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("employees", "job_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("employees", "job_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
