"""add_job_key

Revision ID: 3e51b46dd90f
Revises: 06cfa84778dd
Create Date: 2026-05-28 10:13:32.513926

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3e51b46dd90f"
down_revision: Union[str, Sequence[str], None] = "06cfa84778dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("key", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "key")
    # ### end Alembic commands ###
