"""add_job_short_name

Revision ID: 06cfa84778dd
Revises: e5ed5ba88af4
Create Date: 2026-05-28 09:59:27.666324

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06cfa84778dd"
down_revision: Union[str, Sequence[str], None] = "e5ed5ba88af4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs", sa.Column("short_name", sa.String(length=64), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "short_name")
    # ### end Alembic commands ###
