"""add is_main to employee_department

Revision ID: 7ec50039cf2b
Revises: f035c5d24c0b
Create Date: 2026-05-12 13:44:39.409791

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ec50039cf2b"
down_revision: Union[str, Sequence[str], None] = "f035c5d24c0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee_departments",
        sa.Column("is_main", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee_departments", "is_main")
    # ### end Alembic commands ###
