"""add key field to talent_audit_job_statuses

Revision ID: 2ce5ce34e949
Revises: 126a5cfed6ed
Create Date: 2026-05-22 10:33:49.838250

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2ce5ce34e949"
down_revision: Union[str, Sequence[str], None] = "126a5cfed6ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_group_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("allow_multiple", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_group_types")),
        sa.UniqueConstraint("name", name=op.f("uq_job_group_types_name"))
    )
    op.create_table(
        "job_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_protected", sa.Boolean(), nullable=False),
        sa.Column("job_group_type_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_group_type_id"],
            ["job_group_types.id"],
            name=op.f("fk_job_groups_job_group_type_id_job_group_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_groups")),
        sa.UniqueConstraint("name", name=op.f("uq_job_groups_name"))
    )
    op.create_table(
        "job_job_group_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("job_group_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_group_id"],
            ["job_groups.id"],
            name=op.f("fk_job_job_group_links_job_group_id_job_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_job_group_links_job_id_jobs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_job_group_links")),
        sa.UniqueConstraint("job_id", "job_group_id", name="uq_job_job_group")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("job_job_group_links")
    op.drop_table("job_groups")
    op.drop_table("job_group_types")
    # ### end Alembic commands ###
