"""supervision role: dept links, link_target, active context

Revision ID: 96cf1a9a6659
Revises: 682b01d1bbd6
Create Date: 2026-06-14 15:37:21.227303

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96cf1a9a6659"
down_revision: Union[str, Sequence[str], None] = "682b01d1bbd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "process_role_active_contexts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("process_role_id", sa.Integer(), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f(
                "fk_process_role_active_contexts_department_id_departments"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_process_role_active_contexts_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_role_id"],
            ["process_roles.id"],
            name=op.f(
                "fk_process_role_active_contexts_process_role_id_process_roles"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_process_role_active_contexts")
        ),
        sa.UniqueConstraint("employee_id", name="uq_prac_employee")
    )
    op.create_index(
        op.f("ix_process_role_active_contexts_employee_id"),
        "process_role_active_contexts",
        ["employee_id"],
        unique=False,
    )
    op.create_table(
        "process_role_holder_department_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("process_role_holder_id", sa.Integer(), nullable=False),
        sa.Column("process_role_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f(
                "fk_process_role_holder_department_links_department_id_departments"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_role_holder_id", "process_role_id"],
            [
                "process_role_holders.id",
                "process_role_holders.process_role_id",
            ],
            name="fk_prhd_holder_role",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_process_role_holder_department_links")
        )
    )
    op.create_index(
        op.f("ix_process_role_holder_department_links_department_id"),
        "process_role_holder_department_links",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_process_role_holder_department_links_process_role_holder_id"),
        "process_role_holder_department_links",
        ["process_role_holder_id"],
        unique=False,
    )
    op.add_column(
        "process_roles",
        sa.Column(
            "link_target",
            sa.String(length=16),
            server_default="employee",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("process_roles", "link_target")
    op.drop_index(
        op.f("ix_process_role_holder_department_links_process_role_holder_id"),
        table_name="process_role_holder_department_links",
    )
    op.drop_index(
        op.f("ix_process_role_holder_department_links_department_id"),
        table_name="process_role_holder_department_links",
    )
    op.drop_table("process_role_holder_department_links")
    op.drop_index(
        op.f("ix_process_role_active_contexts_employee_id"),
        table_name="process_role_active_contexts",
    )
    op.drop_table("process_role_active_contexts")
    # ### end Alembic commands ###
