"""add options_source and user_override_allowed to app_settings

Revision ID: b060250c7b73
Revises: 6370e6f0e278
Create Date: 2026-07-01 10:52:06.095180

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b060250c7b73"
down_revision: Union[str, Sequence[str], None] = "6370e6f0e278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "app_settings",
        sa.Column("options_source", sa.String(length=64), nullable=True),
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "user_override_allowed",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_settings", "user_override_allowed")
    op.drop_column("app_settings", "options_source")
    # ### end Alembic commands ###
