"""create planning-related tables

Revision ID: 0e829a8df7aa
Revises: 3e51b46dd90f
Create Date: 2026-05-29 21:06:23.834431

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0e829a8df7aa"
down_revision: Union[str, Sequence[str], None] = "3e51b46dd90f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plan_session_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_session_statuses")),
        sa.UniqueConstraint("key", name=op.f("uq_plan_session_statuses_key"))
    )
    op.create_table(
        "plan_category_defaults",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("department_category_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_category_id"],
            ["department_categories.id"],
            name=op.f(
                "fk_plan_category_defaults_department_category_id_department_categories"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_category_defaults")),
        sa.UniqueConstraint(
            "department_category_id", name="uq_plan_category_default_category"
        )
    )
    op.create_table(
        "plan_sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("plan_session_status_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["plan_session_status_id"],
            ["plan_session_statuses.id"],
            name=op.f(
                "fk_plan_sessions_plan_session_status_id_plan_session_statuses"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_sessions"))
    )
    op.create_table(
        "plan_scope_defaults",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_group_id", sa.Integer(), nullable=False),
        sa.Column("talent_status_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_group_id"],
            ["job_groups.id"],
            name=op.f("fk_plan_scope_defaults_job_group_id_job_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["talent_status_id"],
            ["talent_statuses.id"],
            name=op.f(
                "fk_plan_scope_defaults_talent_status_id_talent_statuses"
            ),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_scope_defaults")),
        sa.UniqueConstraint(
            "job_group_id",
            "talent_status_id",
            name="uq_plan_scope_default_jg_ts",
        )
    )
    op.create_table(
        "plan_scopes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plan_session_id", sa.Integer(), nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("job_group_id", sa.Integer(), nullable=False),
        sa.Column("talent_status_id", sa.Integer(), nullable=True),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "value IS NULL OR (value >= 0 AND value <= 100)",
            name=op.f("ck_plan_scopes_ck_plan_scope_value_range"),
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_plan_scopes_department_id_departments"),
        ),
        sa.ForeignKeyConstraint(
            ["job_group_id"],
            ["job_groups.id"],
            name=op.f("fk_plan_scopes_job_group_id_job_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_session_id"],
            ["plan_sessions.id"],
            name=op.f("fk_plan_scopes_plan_session_id_plan_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["talent_status_id"],
            ["talent_statuses.id"],
            name=op.f("fk_plan_scopes_talent_status_id_talent_statuses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_scopes")),
        sa.UniqueConstraint(
            "plan_session_id",
            "department_id",
            "job_group_id",
            "talent_status_id",
            name="uq_plan_scope_session_dept_jg_ts",
        )
    )
    op.create_table(
        "plan_session_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("plan_session_id", sa.Integer(), nullable=False),
        sa.Column("department_category_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["department_category_id"],
            ["department_categories.id"],
            name=op.f(
                "fk_plan_session_categories_department_category_id_department_categories"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["plan_session_id"],
            ["plan_sessions.id"],
            name=op.f(
                "fk_plan_session_categories_plan_session_id_plan_sessions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plan_session_categories")),
        sa.UniqueConstraint(
            "plan_session_id",
            "department_category_id",
            name="uq_plan_session_category",
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plan_session_categories")
    op.drop_table("plan_scopes")
    op.drop_table("plan_scope_defaults")
    op.drop_table("plan_sessions")
    op.drop_table("plan_category_defaults")
    op.drop_table("plan_session_statuses")
    # ### end Alembic commands ###
