"""add short_name to process roles

Revision ID: e75068745a1d
Revises: dd4299f7b891
Create Date: 2026-07-13 00:12:31.145126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e75068745a1d"
down_revision: Union[str, Sequence[str], None] = "dd4299f7b891"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "process_roles",
        sa.Column("short_name", sa.String(length=32), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("process_roles", "short_name")
    # ### end Alembic commands ###
