"""move employee_language_profiles to person level

Revision ID: b4b41f2e23fe
Revises: ed3b519eced8
Create Date: 2026-07-08 19:37:42.033618

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b4b41f2e23fe"
down_revision: Union[str, Sequence[str], None] = "ed3b519eced8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add nullable, backfill from the owning employee, then tighten to NOT NULL
    # (existing rows would violate a straight NOT NULL add).
    op.add_column(
        "employee_language_profiles",
        sa.Column("person_id", sa.Integer(), nullable=True),
    )
    op.execute(
        "UPDATE employee_language_profiles lp "
        "SET person_id = e.person_id "
        "FROM employees e WHERE e.id = lp.employee_id"
    )
    op.alter_column("employee_language_profiles", "person_id", nullable=False)
    op.drop_constraint(
        op.f("uq_employee_language_profiles_employee_id"),
        "employee_language_profiles",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_employee_language_profiles_person_id"),
        "employee_language_profiles",
        ["person_id"],
    )
    op.drop_constraint(
        op.f("fk_employee_language_profiles_employee_id_employees"),
        "employee_language_profiles",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_employee_language_profiles_person_id_persons"),
        "employee_language_profiles",
        "persons",
        ["person_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("employee_language_profiles", "employee_id")
    op.drop_constraint(
        op.f("fk_employee_languages_profile_id_employee_language_profiles"),
        "employee_languages",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_employee_languages_profile_id_employee_language_profiles"),
        "employee_languages",
        "employee_language_profiles",
        ["profile_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_employee_languages_profile_id_employee_language_profiles"),
        "employee_languages",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_employee_languages_profile_id_employee_language_profiles"),
        "employee_languages",
        "employee_language_profiles",
        ["profile_id"],
        ["id"],
    )
    op.add_column(
        "employee_language_profiles",
        sa.Column(
            "employee_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    # Reverse backfill: pick the lowest-id employee linked to the person.
    op.execute(
        "UPDATE employee_language_profiles lp "
        "SET employee_id = ("
        "SELECT min(e.id) FROM employees e WHERE e.person_id = lp.person_id"
        ")"
    )
    op.alter_column("employee_language_profiles", "employee_id", nullable=False)
    op.drop_constraint(
        op.f("fk_employee_language_profiles_person_id_persons"),
        "employee_language_profiles",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_employee_language_profiles_employee_id_employees"),
        "employee_language_profiles",
        "employees",
        ["employee_id"],
        ["id"],
    )
    op.drop_constraint(
        op.f("uq_employee_language_profiles_person_id"),
        "employee_language_profiles",
        type_="unique",
    )
    op.create_unique_constraint(
        op.f("uq_employee_language_profiles_employee_id"),
        "employee_language_profiles",
        ["employee_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("employee_language_profiles", "person_id")
    # ### end Alembic commands ###
