"""add recruitment module tables

Revision ID: 2fb545f92aa0
Revises: e48b3186eb5c
Create Date: 2026-07-15 06:55:29.939052

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2fb545f92aa0"
down_revision: Union[str, Sequence[str], None] = "e48b3186eb5c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recruitment_dimensions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recruitment_dimensions")),
        sa.UniqueConstraint("key", name=op.f("uq_recruitment_dimensions_key")),
        sa.UniqueConstraint(
            "name", name=op.f("uq_recruitment_dimensions_name")
        )
    )
    op.create_table(
        "recruitment_task_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_recruitment_task_statuses")
        ),
        sa.UniqueConstraint(
            "name", name=op.f("uq_recruitment_task_statuses_name")
        )
    )
    op.create_table(
        "job_requirement_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
            name=op.f("fk_job_requirement_groups_created_by_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_job_requirement_groups_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_requirement_groups"))
    )
    op.create_table(
        "job_requirement_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("dimension_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dimension_id"],
            ["recruitment_dimensions.id"],
            name=op.f(
                "fk_job_requirement_items_dimension_id_recruitment_dimensions"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["job_requirement_groups.id"],
            name=op.f(
                "fk_job_requirement_items_group_id_job_requirement_groups"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_requirement_items"))
    )
    op.create_table(
        "recruitment_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("requirement_group_id", sa.Integer(), nullable=True),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("target_deadline", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("in_process_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
            name=op.f("fk_recruitment_tasks_created_by_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_recruitment_tasks_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["requirement_group_id"],
            ["job_requirement_groups.id"],
            name=op.f(
                "fk_recruitment_tasks_requirement_group_id_job_requirement_groups"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["recruitment_task_statuses.id"],
            name=op.f(
                "fk_recruitment_tasks_status_id_recruitment_task_statuses"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recruitment_tasks"))
    )
    # ### end Alembic commands ###

    # --- seed data (hand-appended) ------------------------------------------
    # Fixed status set — matched by name by the recruitment task state machine.
    op.execute(
        """
        INSERT INTO recruitment_task_statuses (name, description) VALUES
            ('created',    'Task registered; not yet in work'),
            ('in_process', 'Recruiter is working the task'),
            ('fulfilled',  'Closed successfully — position filled'),
            ('rejected',   'Closed without hire — cancelled/rejected')
        """
    )
    # Menu item (sort_order 45 = between training 40 and admin 50). Starts
    # hidden from everyone-with-no-group; visibility comes from the group links
    # below. label_key/icon 'recruitment' resolve on the frontend.
    op.execute(
        """
        INSERT INTO menus (key, label_key, path, icon, parent_id, sort_order,
                           is_active, visible_to_all_groups, visible_to_regular)
        VALUES ('recruitment', 'recruitment', '/recruitment', 'recruitment',
                NULL, 45, TRUE, FALSE, FALSE)
        ON CONFLICT (key) DO NOTHING
        """
    )
    # Visible ONLY to HRS / HRM / admin / dev — matched case-insensitively by
    # group id (never by name in app code, but the seed resolves ids by name).
    op.execute(
        """
        INSERT INTO menu_user_group_links (menu_id, user_group_id)
        SELECT m.id, g.id
        FROM menus m, user_groups g
        WHERE m.key = 'recruitment'
          AND lower(g.name) IN ('hrs', 'hrm', 'admin', 'dev')
        ON CONFLICT (menu_id, user_group_id) DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Remove hand-seeded rows before dropping tables.
    op.execute(
        """
        DELETE FROM menu_user_group_links
        WHERE menu_id IN (SELECT id FROM menus WHERE key = 'recruitment')
        """
    )
    op.execute("DELETE FROM menus WHERE key = 'recruitment'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recruitment_tasks")
    op.drop_table("job_requirement_items")
    op.drop_table("job_requirement_groups")
    op.drop_table("recruitment_task_statuses")
    op.drop_table("recruitment_dimensions")
    # ### end Alembic commands ###
