"""add persons table and employees person_id

Revision ID: b22b673caf3f
Revises: c8d2e5f7a913
Create Date: 2026-07-07 23:54:55.105616

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b22b673caf3f"
down_revision: Union[str, Sequence[str], None] = "c8d2e5f7a913"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.String(length=64), nullable=True),
        sa.Column("last_name", sa.String(length=64), nullable=True),
        sa.Column("patronymic", sa.String(length=64), nullable=True),
        sa.Column("sex", sa.String(length=8), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column(
            "name_dedupe_no", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_persons")),
        sa.UniqueConstraint(
            "last_name",
            "first_name",
            "name_dedupe_no",
            name="uq_persons_last_first_dedupe",
        )
    )
    op.add_column(
        "employees", sa.Column("person_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        op.f("fk_employees_person_id_persons"),
        "employees",
        "persons",
        ["person_id"],
        ["id"],
    )
    # ### end Alembic commands ###

    # ── Data: register the essence + mirror employee's permission grants ─────
    op.execute(
        "INSERT INTO essences (name, description) VALUES ('person', 'person') "
        "ON CONFLICT DO NOTHING"
    )
    # One (verb, person) permission row for every verb employee already has.
    op.execute(
        """
        INSERT INTO operation_essence_links (operation_id, essence_id)
        SELECT oel.operation_id, (SELECT id FROM essences WHERE name = 'person')
        FROM operation_essence_links oel
        JOIN essences e ON e.id = oel.essence_id AND e.name = 'employee'
        ON CONFLICT DO NOTHING
        """
    )
    # Every group holding a (verb, employee) grant gets the matching
    # (verb, person) grant — HR users must reach /persons/check_name etc.
    op.execute(
        """
        INSERT INTO user_group_operation_essence_links
            (user_group_id, operation_essence_link_id)
        SELECT ugoel.user_group_id, poel.id
        FROM user_group_operation_essence_links ugoel
        JOIN operation_essence_links eoel
            ON eoel.id = ugoel.operation_essence_link_id
        JOIN essences e ON e.id = eoel.essence_id AND e.name = 'employee'
        JOIN operation_essence_links poel
            ON poel.operation_id = eoel.operation_id
           AND poel.essence_id = (SELECT id FROM essences WHERE name = 'person')
        ON CONFLICT DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # essences delete cascades to operation_essence_links and on to
    # user_group_operation_essence_links (both FKs are ON DELETE CASCADE).
    op.execute("DELETE FROM essences WHERE name = 'person'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_employees_person_id_persons"), "employees", type_="foreignkey"
    )
    op.drop_column("employees", "person_id")
    op.drop_table("persons")
    # ### end Alembic commands ###
