"""add job_assigned_date to employee_personal_data

Revision ID: db95afdcd069
Revises: d51c4e989a61
Create Date: 2026-06-12 14:17:33.517162

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "db95afdcd069"
down_revision: Union[str, Sequence[str], None] = "d51c4e989a61"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee_personal_data",
        sa.Column("job_assigned_date", sa.Date(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee_personal_data", "job_assigned_date")
    # ### end Alembic commands ###
