"""set sort_order to department_categories not nullable

Revision ID: 39fdc03387dd
Revises: b9426bc94b77
Create Date: 2026-06-26 16:20:37.853816

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "39fdc03387dd"
down_revision: Union[str, Sequence[str], None] = "b9426bc94b77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "department_categories",
        "sort_order",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "department_categories",
        "sort_order",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###
