"""add openings to recruitment_tasks

Revision ID: 7cb556f124fc
Revises: a4014dfde1e9
Create Date: 2026-07-16 10:10:51.320389

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7cb556f124fc"
down_revision: Union[str, Sequence[str], None] = "a4014dfde1e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recruitment_tasks",
        sa.Column(
            "openings", sa.Integer(), server_default="1", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recruitment_tasks", "openings")
    # ### end Alembic commands ###
