"""mission status + drop duration_months

Revision ID: dafe3b95ca2f
Revises: 5481033843c6
Create Date: 2026-07-21 22:45:05.893275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "dafe3b95ca2f"
down_revision: Union[str, Sequence[str], None] = "5481033843c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_mission_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_employee_mission_statuses")
        ),
        sa.UniqueConstraint(
            "key", name=op.f("uq_employee_mission_statuses_key")
        )
    )
    # --- seed the three statuses -------------------------------------------
    # status_id is NOT NULL, so the rows it points at must exist before the
    # column does. Seeded here rather than left to seed_mission_statuses.py so
    # this revision is self-contained on a fresh database.
    op.execute(
        """
        INSERT INTO employee_mission_statuses (key, description, sort_order)
        VALUES ('planned',    'No KPI progress recorded yet',   10),
               ('in_process', 'At least one KPI has progress',  20),
               ('completed',  'Every KPI reached 100%',         30)
        ON CONFLICT (key) DO NOTHING
        """
    )

    # --- add the column nullable, backfill, THEN tighten --------------------
    # Adding it NOT NULL outright fails on every existing mission.
    op.add_column(
        "employee_missions",
        sa.Column("status_id", sa.Integer(), nullable=True),
    )
    # Mirrors compute_status_key() exactly: a mission with no KPIs is 'planned'
    # (not 'completed' — "done because nothing was asked" would be wrong).
    op.execute(
        """
        UPDATE employee_missions m
        SET status_id = (
            SELECT s.id FROM employee_mission_statuses s
            WHERE s.key = CASE
                WHEN NOT EXISTS (
                    SELECT 1 FROM employee_mission_kpis k WHERE k.mission_id = m.id
                ) THEN 'planned'
                WHEN NOT EXISTS (
                    SELECT 1 FROM employee_mission_kpis k
                    WHERE k.mission_id = m.id AND k.percent < 100
                ) THEN 'completed'
                WHEN EXISTS (
                    SELECT 1 FROM employee_mission_kpis k
                    WHERE k.mission_id = m.id AND k.percent > 0
                ) THEN 'in_process'
                ELSE 'planned'
            END
        )
        """
    )
    op.alter_column("employee_missions", "status_id", nullable=False)
    op.create_index(
        op.f("ix_employee_missions_status_id"),
        "employee_missions",
        ["status_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_employee_missions_status_id_employee_mission_statuses"),
        "employee_missions",
        "employee_mission_statuses",
        ["status_id"],
        ["id"],
        ondelete="RESTRICT",
    )

    # --- duration_months is now derived from the period --------------------
    # Nothing is lost: it is exactly months_between(start_date, end_date).
    op.drop_column("employee_missions", "duration_months")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    duration_months is restored by RECOMPUTING it from the period, so the
    round-trip is lossless. The status rows/column simply go away.
    """
    op.add_column(
        "employee_missions",
        sa.Column("duration_months", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.execute(
        """
        UPDATE employee_missions
        SET duration_months = GREATEST(
            0,
            (DATE_PART('year', AGE(end_date, start_date)) * 12
             + DATE_PART('month', AGE(end_date, start_date)))::int
        )
        """
    )
    op.alter_column("employee_missions", "duration_months", nullable=False)
    op.drop_constraint(
        op.f("fk_employee_missions_status_id_employee_mission_statuses"),
        "employee_missions",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_employee_missions_status_id"), table_name="employee_missions"
    )
    op.drop_column("employee_missions", "status_id")
    op.drop_table("employee_mission_statuses")
