"""add access_test_contexts

Revision ID: ddcba7c0a2d5
Revises: b4b41f2e23fe
Create Date: 2026-07-09 18:15:12.412841

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ddcba7c0a2d5"
down_revision: Union[str, Sequence[str], None] = "b4b41f2e23fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_test_contexts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("group_ids", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_access_test_contexts_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_test_contexts")),
        sa.UniqueConstraint("employee_id", name="uq_access_test_employee")
    )
    op.create_index(
        op.f("ix_access_test_contexts_employee_id"),
        "access_test_contexts",
        ["employee_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_access_test_contexts_employee_id"),
        table_name="access_test_contexts",
    )
    op.drop_table("access_test_contexts")
    # ### end Alembic commands ###
