"""rse status lookup and feedback rows

Creates the three tables and adds `review_session_employee_status_id` as a
NULLABLE column. The old `status` varchar and the `employee_feedback` /
`manager_feedback` columns are left in place for
backend/scripts/migrate_status_and_feedback.py to read; a later revision
backfills-then-tightens the FK and drops all three.

Revision ID: 92272f5c7c50
Revises: 9fc8d31b01a0
Create Date: 2026-07-22 21:57:08.830371

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "92272f5c7c50"
down_revision: Union[str, Sequence[str], None] = "9fc8d31b01a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_session_employee_feedback_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "description",
            sa.String(length=256),
            server_default="",
            nullable=False,
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_session_employee_feedback_types")
        ),
        sa.UniqueConstraint(
            "key", name=op.f("uq_review_session_employee_feedback_types_key")
        )
    )
    op.create_table(
        "review_session_employee_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column(
            "description",
            sa.String(length=256),
            server_default="",
            nullable=False,
        ),
        sa.Column(
            "sort_order", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_session_employee_statuses")
        ),
        sa.UniqueConstraint(
            "key", name=op.f("uq_review_session_employee_statuses_key")
        )
    )
    op.create_table(
        "review_session_employee_feedbacks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("review_session_employee_id", sa.Integer(), nullable=False),
        sa.Column(
            "review_session_employee_feedback_type_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["review_session_employee_feedback_type_id"],
            ["review_session_employee_feedback_types.id"],
            name=op.f(
                "fk_review_session_employee_feedbacks_review_session_employee_feedback_type_id_review_session_employee_feedback_types"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["review_session_employee_id"],
            ["review_session_employees.id"],
            name=op.f(
                "fk_review_session_employee_feedbacks_review_session_employee_id_review_session_employees"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_session_employee_feedbacks")
        ),
        sa.UniqueConstraint(
            "review_session_employee_id",
            "review_session_employee_feedback_type_id",
            name="uq_review_session_employee_feedback",
        )
    )
    op.create_index(
        op.f(
            "ix_review_session_employee_feedbacks_review_session_employee_id"
        ),
        "review_session_employee_feedbacks",
        ["review_session_employee_id"],
        unique=False,
    )
    op.add_column(
        "review_session_employees",
        # NULLABLE on purpose: existing rows have no value yet. The data move
        # backfills it from the old `status` varchar, and the NEXT revision
        # tightens it to NOT NULL. Same staging the missions status used.
        sa.Column(
            "review_session_employee_status_id", sa.Integer(), nullable=True
        ),
    )
    op.create_foreign_key(
        op.f(
            "fk_review_session_employees_review_session_employee_status_id_review_session_employee_statuses"
        ),
        "review_session_employees",
        "review_session_employee_statuses",
        ["review_session_employee_status_id"],
        ["id"],
    )
    # NOTE: `status`, `employee_feedback` and `manager_feedback` are deliberately
    # NOT dropped here. backend/scripts/migrate_status_and_feedback.py reads them
    # to populate the new column and rows; the drop is its own later revision, so
    # a database still holding data has somewhere to move it to.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f(
            "fk_review_session_employees_review_session_employee_status_id_review_session_employee_statuses"
        ),
        "review_session_employees",
        type_="foreignkey",
    )
    op.drop_column(
        "review_session_employees", "review_session_employee_status_id"
    )
    op.drop_index(
        op.f(
            "ix_review_session_employee_feedbacks_review_session_employee_id"
        ),
        table_name="review_session_employee_feedbacks",
    )
    op.drop_table("review_session_employee_feedbacks")
    op.drop_table("review_session_employee_statuses")
    op.drop_table("review_session_employee_feedback_types")
    # ### end Alembic commands ###
