"""add review_session_employee_comments table

Revision ID: 5648aeef1b97
Revises: 96cf1a9a6659
Create Date: 2026-06-16 07:29:17.730566

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5648aeef1b97"
down_revision: Union[str, Sequence[str], None] = "96cf1a9a6659"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_session_employee_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("review_session_employee_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("author_role", sa.String(length=20), nullable=False),
        sa.Column(
            "visibility",
            sa.String(length=10),
            server_default="private",
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["employees.id"],
            name=op.f(
                "fk_review_session_employee_comments_author_id_employees"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["review_session_employee_id"],
            ["review_session_employees.id"],
            name=op.f(
                "fk_review_session_employee_comments_review_session_employee_id_review_session_employees"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_session_employee_comments")
        )
    )
    op.create_unique_constraint(
        "uq_rse_session_employee",
        "review_session_employees",
        ["session_id", "employee_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_rse_session_employee", "review_session_employees", type_="unique"
    )
    op.drop_table("review_session_employee_comments")
    # ### end Alembic commands ###
