"""add key field to talent_audit_job_statuses

Revision ID: 126a5cfed6ed
Revises: dfdf4f471270
Create Date: 2026-05-22 09:44:45.020537

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "126a5cfed6ed"
down_revision: Union[str, Sequence[str], None] = "dfdf4f471270"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add as NULLABLE first
    op.add_column(
        "talent_audit_job_statuses",
        sa.Column("key", sa.String(32), nullable=True),
    )

    # 2. Backfill — set key values for existing rows
    #    Adjust these if your existing statuses have different names/ids
    op.execute("UPDATE talent_audit_job_statuses SET key = 'created' WHERE id = 1")
    op.execute("UPDATE talent_audit_job_statuses SET key = 'closed' WHERE id = 2")
    # If id=2 doesn't exist yet, insert it:
    # op.execute("INSERT INTO talent_audit_job_statuses (id, name, key) VALUES (2, 'закрито', 'closed')")

    # 3. Make NOT NULL + UNIQUE
    op.alter_column("talent_audit_job_statuses", "key", nullable=False)
    op.create_unique_constraint("uq_talent_audit_job_statuses_key", "talent_audit_job_statuses", ["key"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_talent_audit_job_statuses_key"),
        "talent_audit_job_statuses",
        type_="unique",
    )
    op.drop_column("talent_audit_job_statuses", "key")
    # ### end Alembic commands ###
