"""employee children + sex/marital on personal data

Revision ID: fd30ccf1085a
Revises: db95afdcd069
Create Date: 2026-06-13 15:01:56.471006

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fd30ccf1085a"
down_revision: Union[str, Sequence[str], None] = "db95afdcd069"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_children",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("birth_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_children_employee_id_employees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_children")),
    )
    op.add_column(
        "employee_personal_data",
        sa.Column("sex", sa.String(length=8), nullable=True),
    )
    op.add_column(
        "employee_personal_data",
        sa.Column("marital_status", sa.String(length=16), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee_personal_data", "marital_status")
    op.drop_column("employee_personal_data", "sex")
    op.drop_table("employee_children")
    # ### end Alembic commands ###
