"""add is_main property to department categories

Revision ID: 8df4cfcf1022
Revises: 30355878249f
Create Date: 2026-05-21 10:38:14.970845

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8df4cfcf1022"
down_revision: Union[str, Sequence[str], None] = "30355878249f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "department_categories",
        sa.Column("is_main", sa.Boolean(), nullable=True),
    )
    op.drop_constraint(
        op.f("uq_department_categories_key"),
        "department_categories",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("uq_department_categories_key"),
        "department_categories",
        ["key"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("department_categories", "is_main")
    # ### end Alembic commands ###
