"""add code to empl_event_type

Revision ID: fc204ea8b525
Revises: da390730e78d
Create Date: 2026-05-23 10:53:30.223214

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc204ea8b525"
down_revision: Union[str, Sequence[str], None] = "da390730e78d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employee_event_types",
        sa.Column("code", sa.String(length=64), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employee_event_types", "code")
    # ### end Alembic commands ###
