"""move current_level to employee_current_levels link table

Revision ID: 4bbd3a052d35
Revises: d423b8aaae01
Create Date: 2026-06-12 11:54:22.303143

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bbd3a052d35"
down_revision: Union[str, Sequence[str], None] = "d423b8aaae01"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_current_levels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("level_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_current_levels_employee_id_employees"),
        ),
        sa.ForeignKeyConstraint(
            ["level_id"],
            ["review_levels.id"],
            name=op.f("fk_employee_current_levels_level_id_review_levels"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_current_levels")),
        sa.UniqueConstraint(
            "employee_id", name="uq_employee_current_level_employee_id"
        ),
    )
    # Carry existing assignments into the new link table BEFORE dropping the
    # column — autogenerate does not migrate data.
    op.execute(
        "INSERT INTO employee_current_levels (employee_id, level_id, created_at) "
        "SELECT id, current_level_id, now() FROM employees "
        "WHERE current_level_id IS NOT NULL"
    )
    op.drop_constraint(
        op.f("fk_employees_current_level_id_review_levels"),
        "employees",
        type_="foreignkey",
    )
    op.drop_column("employees", "current_level_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column(
            "current_level_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        op.f("fk_employees_current_level_id_review_levels"),
        "employees",
        "review_levels",
        ["current_level_id"],
        ["id"],
    )
    # Restore assignments back onto the column before dropping the link table.
    op.execute(
        "UPDATE employees e SET current_level_id = ecl.level_id "
        "FROM employee_current_levels ecl WHERE ecl.employee_id = e.id"
    )
    op.drop_table("employee_current_levels")
    # ### end Alembic commands ###
