"""add candidates and hiring pipeline tables

Revision ID: b48553770211
Revises: ed6d9c35f600
Create Date: 2026-07-15 22:12:57.171243

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b48553770211"
down_revision: Union[str, Sequence[str], None] = "ed6d9c35f600"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_sources")),
        sa.UniqueConstraint("key", name=op.f("uq_candidate_sources_key"))
    )
    op.create_table(
        "pipeline_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pipeline_statuses")),
        sa.UniqueConstraint("name", name=op.f("uq_pipeline_statuses_name"))
    )
    op.create_table(
        "candidates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.String(length=128), nullable=False),
        sa.Column("last_name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=128), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
            name=op.f("fk_candidates_created_by_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["candidate_sources.id"],
            name=op.f("fk_candidates_source_id_candidate_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidates")),
        sa.UniqueConstraint("email", name=op.f("uq_candidates_email"))
    )
    op.create_table(
        "candidate_notes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["employees.id"],
            name=op.f("fk_candidate_notes_author_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_candidate_notes_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_notes"))
    )
    op.create_table(
        "candidate_phones",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_candidate_phones_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_phones"))
    )
    op.create_table(
        "candidate_applications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("candidate_id", sa.Integer(), nullable=False),
        sa.Column("recruitment_task_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["candidates.id"],
            name=op.f("fk_candidate_applications_candidate_id_candidates"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
            name=op.f("fk_candidate_applications_created_by_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recruitment_task_id"],
            ["recruitment_tasks.id"],
            name=op.f(
                "fk_candidate_applications_recruitment_task_id_recruitment_tasks"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["pipeline_statuses.id"],
            name=op.f("fk_candidate_applications_status_id_pipeline_statuses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_applications")),
        sa.UniqueConstraint(
            "candidate_id",
            "recruitment_task_id",
            name="uq_candidate_application_candidate_task",
        )
    )
    op.create_table(
        "application_status_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("changed_by", sa.Integer(), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["candidate_applications.id"],
            name=op.f(
                "fk_application_status_history_application_id_candidate_applications"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["employees.id"],
            name=op.f("fk_application_status_history_changed_by_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["pipeline_statuses.id"],
            name=op.f(
                "fk_application_status_history_status_id_pipeline_statuses"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_application_status_history")
        )
    )
    # ### end Alembic commands ###

    # --- seed data (hand-appended) ------------------------------------------
    # Fixed pipeline stage set — matched by name by the pipeline state machine.
    # sort_order drives the kanban column order and the "furthest stage" logic.
    op.execute(
        """
        INSERT INTO pipeline_statuses (name, description, sort_order) VALUES
            ('applied',   'Candidate applied / added to the task', 0),
            ('screen',    'Screening in progress',                 1),
            ('interview', 'Interview stage',                       2),
            ('offer',     'Offer extended',                        3),
            ('hired',     'Hired — position filled',               4),
            ('rejected',  'Rejected / withdrawn',                  5)
        """
    )
    # Candidates menu item (sort_order 46 = right after recruitment 45). Starts
    # hidden; visibility comes from the group links below. label_key/icon
    # 'candidates' resolve on the frontend.
    op.execute(
        """
        INSERT INTO menus (key, label_key, path, icon, parent_id, sort_order,
                           is_active, visible_to_all_groups, visible_to_regular)
        VALUES ('candidates', 'candidates', '/candidates', 'candidates',
                NULL, 46, TRUE, FALSE, FALSE)
        ON CONFLICT (key) DO NOTHING
        """
    )
    # Visible ONLY to HRS / HRM / admin / dev (same 4 roles as recruitment).
    op.execute(
        """
        INSERT INTO menu_user_group_links (menu_id, user_group_id)
        SELECT m.id, g.id
        FROM menus m, user_groups g
        WHERE m.key = 'candidates'
          AND lower(g.name) IN ('hrs', 'hrm', 'admin', 'dev')
        ON CONFLICT (menu_id, user_group_id) DO NOTHING
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Remove hand-seeded rows before dropping tables.
    op.execute(
        """
        DELETE FROM menu_user_group_links
        WHERE menu_id IN (SELECT id FROM menus WHERE key = 'candidates')
        """
    )
    op.execute("DELETE FROM menus WHERE key = 'candidates'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("application_status_history")
    op.drop_table("candidate_applications")
    op.drop_table("candidate_phones")
    op.drop_table("candidate_notes")
    op.drop_table("candidates")
    op.drop_table("pipeline_statuses")
    op.drop_table("candidate_sources")
    # ### end Alembic commands ###
