"""add department_type_parental_link table and relationships

Revision ID: 307351b26ddb
Revises: 831dd487e19a
Create Date: 2026-05-18 20:22:25.716825

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "307351b26ddb"
down_revision: Union[str, Sequence[str], None] = "831dd487e19a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "department_type_parental_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("child_id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["child_id"],
            ["department_types.id"],
            name=op.f(
                "fk_department_type_parental_links_child_id_department_types"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["department_types.id"],
            name=op.f(
                "fk_department_type_parental_links_parent_id_department_types"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_department_type_parental_links")
        ),
        sa.UniqueConstraint(
            "child_id",
            "parent_id",
            name="uq_dept_type_parental_link_child_parent",
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("department_type_parental_links")
    # ### end Alembic commands ###
