"""restructure talent_audit_interview: add talent_audit_id, remove talent_audit_job_id and talent_status_period_link_id, create talent_audit_interview_job link table with created_by

Revision ID: 8d1c0f55930c
Revises: d7439cc54970
Create Date: 2026-05-21 21:45:15.639818

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d1c0f55930c"
down_revision: Union[str, Sequence[str], None] = "d7439cc54970"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "talent_audit_interview_job",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("talent_audit_interview_id", sa.Integer(), nullable=False),
        sa.Column("talent_audit_job_id", sa.Integer(), nullable=False),
        sa.Column("talent_status_period_link_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
            name=op.f("fk_talent_audit_interview_job_created_by_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["talent_audit_interview_id"],
            ["talent_audit_interview.id"],
            name=op.f(
                "fk_talent_audit_interview_job_talent_audit_interview_id_talent_audit_interview"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["talent_audit_job_id"],
            ["talent_audit_job.id"],
            name=op.f(
                "fk_talent_audit_interview_job_talent_audit_job_id_talent_audit_job"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["talent_status_period_link_id"],
            ["talent_status_period_link.id"],
            name=op.f(
                "fk_talent_audit_interview_job_talent_status_period_link_id_talent_status_period_link"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_talent_audit_interview_job")),
        sa.UniqueConstraint(
            "talent_audit_interview_id",
            "talent_audit_job_id",
            name="uq_interview_job",
        ),
    )
    op.add_column(
        "talent_audit_interview",
        sa.Column("talent_audit_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(
        op.f("fk_talent_audit_interview_talent_status_period_link_id__9c73"),
        "talent_audit_interview",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_talent_audit_interview_talent_audit_job_id_talent_audit_job"),
        "talent_audit_interview",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_talent_audit_interview_talent_audit_id_talent_audit"),
        "talent_audit_interview",
        "talent_audit",
        ["talent_audit_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("talent_audit_interview", "talent_status_period_link_id")
    op.drop_column("talent_audit_interview", "talent_audit_job_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "talent_audit_interview",
        sa.Column(
            "talent_audit_job_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "talent_audit_interview",
        sa.Column(
            "talent_status_period_link_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(
        op.f("fk_talent_audit_interview_talent_audit_id_talent_audit"),
        "talent_audit_interview",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_talent_audit_interview_talent_audit_job_id_talent_audit_job"),
        "talent_audit_interview",
        "talent_audit_job",
        ["talent_audit_job_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_talent_audit_interview_talent_status_period_link_id__9c73"),
        "talent_audit_interview",
        "talent_status_period_link",
        ["talent_status_period_link_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_column("talent_audit_interview", "talent_audit_id")
    op.drop_table("talent_audit_interview_job")
    # ### end Alembic commands ###
