"""add department_job_targets table

Revision ID: d4169f80d106
Revises: df6b1794c6eb
Create Date: 2026-07-12 04:10:43.665734

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4169f80d106"
down_revision: Union[str, Sequence[str], None] = "df6b1794c6eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "department_job_targets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("department_type_job_link_id", sa.Integer(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "qty >= 0",
            name=op.f(
                "ck_department_job_targets_ck_department_job_targets_qty_nonneg"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("fk_department_job_targets_department_id_departments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["department_type_job_link_id"],
            ["department_type_job_links.id"],
            name=op.f(
                "fk_department_job_targets_department_type_job_link_id_department_type_job_links"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_department_job_targets")),
        sa.UniqueConstraint(
            "department_id",
            "department_type_job_link_id",
            "effective_date",
            name="idx_uq_department_job_target_date",
        )
    )
    op.create_index(
        op.f("ix_department_job_targets_department_id"),
        "department_job_targets",
        ["department_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_department_job_targets_department_type_job_link_id"),
        "department_job_targets",
        ["department_type_job_link_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_department_job_targets_department_type_job_link_id"),
        table_name="department_job_targets",
    )
    op.drop_index(
        op.f("ix_department_job_targets_department_id"),
        table_name="department_job_targets",
    )
    op.drop_table("department_job_targets")
    # ### end Alembic commands ###
