"""add process role subsystem (process, process_role, process_role_holder, process_role_holder_employee_link)

Revision ID: 682b01d1bbd6
Revises: 6cb5ebe8d096
Create Date: 2026-06-14 09:42:32.778525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "682b01d1bbd6"
down_revision: Union[str, Sequence[str], None] = "6cb5ebe8d096"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_processes")),
        sa.UniqueConstraint("key", name="uq_process_key")
    )
    op.create_table(
        "process_roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("process_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["process_id"],
            ["processes.id"],
            name=op.f("fk_process_roles_process_id_processes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_roles")),
        sa.UniqueConstraint(
            "process_id", "key", name="uq_process_role_process_key"
        )
    )
    op.create_index(
        op.f("ix_process_roles_process_id"),
        "process_roles",
        ["process_id"],
        unique=False,
    )
    op.create_table(
        "process_role_holders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("process_role_id", sa.Integer(), nullable=False),
        sa.Column("holder_employee_id", sa.Integer(), nullable=False),
        sa.Column("assigned_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["employees.id"],
            name=op.f("fk_process_role_holders_assigned_by_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["holder_employee_id"],
            ["employees.id"],
            name=op.f("fk_process_role_holders_holder_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_role_id"],
            ["process_roles.id"],
            name=op.f("fk_process_role_holders_process_role_id_process_roles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_process_role_holders")),
        sa.UniqueConstraint("id", "process_role_id", name="uq_prh_id_role"),
        sa.UniqueConstraint(
            "process_role_id", "holder_employee_id", name="uq_prh_role_holder"
        )
    )
    op.create_index(
        op.f("ix_process_role_holders_holder_employee_id"),
        "process_role_holders",
        ["holder_employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_process_role_holders_process_role_id"),
        "process_role_holders",
        ["process_role_id"],
        unique=False,
    )
    op.create_table(
        "process_role_holder_employee_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("process_role_holder_id", sa.Integer(), nullable=False),
        sa.Column("process_role_id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f(
                "fk_process_role_holder_employee_links_employee_id_employees"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["process_role_holder_id", "process_role_id"],
            [
                "process_role_holders.id",
                "process_role_holders.process_role_id",
            ],
            name="fk_prhe_holder_role",
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_process_role_holder_employee_links")
        ),
        sa.UniqueConstraint(
            "process_role_id", "employee_id", name="uq_prhe_role_employee"
        )
    )
    op.create_index(
        op.f("ix_process_role_holder_employee_links_employee_id"),
        "process_role_holder_employee_links",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_process_role_holder_employee_links_process_role_holder_id"),
        "process_role_holder_employee_links",
        ["process_role_holder_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_process_role_holder_employee_links_process_role_holder_id"),
        table_name="process_role_holder_employee_links",
    )
    op.drop_index(
        op.f("ix_process_role_holder_employee_links_employee_id"),
        table_name="process_role_holder_employee_links",
    )
    op.drop_table("process_role_holder_employee_links")
    op.drop_index(
        op.f("ix_process_role_holders_process_role_id"),
        table_name="process_role_holders",
    )
    op.drop_index(
        op.f("ix_process_role_holders_holder_employee_id"),
        table_name="process_role_holders",
    )
    op.drop_table("process_role_holders")
    op.drop_index(
        op.f("ix_process_roles_process_id"), table_name="process_roles"
    )
    op.drop_table("process_roles")
    op.drop_table("processes")
    # ### end Alembic commands ###
