"""add menus table with seed

Revision ID: 890afa13d30a
Revises: 678c55a7d03e
Create Date: 2026-07-05 10:39:31.578257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "890afa13d30a"
down_revision: Union[str, Sequence[str], None] = "678c55a7d03e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menus",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("label_key", sa.String(length=128), nullable=False),
        sa.Column("path", sa.String(length=128), nullable=False),
        sa.Column("icon", sa.String(length=64), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("allowed_groups", sa.String(length=256), nullable=True),
        sa.Column("visible_to_regular", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["menus.id"],
            name=op.f("fk_menus_parent_id_menus"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_menus")),
        sa.UniqueConstraint("key", name=op.f("uq_menus_key"))
    )

    # Seed: ports the former hardcoded MENU_ACCESS map (menuVisibility.ts).
    # allowed_groups NULL = every user with >=1 group; visible_to_regular also
    # shows the item to users WITHOUT any group ('only me' regular users).
    op.execute(
        """
        INSERT INTO menus (key, label_key, path, icon, parent_id, sort_order,
                           is_active, allowed_groups, visible_to_regular) VALUES
        ('employees',     'employees', '/employees',     'people',    NULL, 10, TRUE, NULL,              FALSE),
        ('planning',      'planning',  '/planning',      'insights',  NULL, 20, TRUE, 'dev,admin,hrs',   FALSE),
        ('people_review', 'review',    '/people_review', 'review',    NULL, 30, TRUE, NULL,              TRUE),
        ('training',      'training',  '/training',      'school',    NULL, 40, TRUE, NULL,              FALSE),
        ('admin',         'admin',     '/admin',         'adminPanel',NULL, 50, TRUE, 'dev,admin',       FALSE),
        ('developer',     'developer', '/developer',     'code',      NULL, 60, TRUE, 'dev',             FALSE)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("menus")
    # ### end Alembic commands ###
