"""per-descriptor criterion scores + evaluation mean_score

Revision ID: d423b8aaae01
Revises: 6d4d61fc6fec
Create Date: 2026-06-11 20:09:56.622101

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d423b8aaae01"
down_revision: Union[str, Sequence[str], None] = "6d4d61fc6fec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_session_employee_criterion_scores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "review_session_employee_evaluation_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column("criterion_index", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "score >= 1 AND score <= 4",
            name=op.f(
                "ck_review_session_employee_criterion_scores_ck_criterion_score_range"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["review_session_employee_evaluation_id"],
            ["review_session_employee_evaluations.id"],
            name=op.f(
                "fk_review_session_employee_criterion_scores_review_session_employee_evaluation_id_review_session_employee_evaluations"
            ),
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_review_session_employee_criterion_scores")
        ),
        sa.UniqueConstraint(
            "review_session_employee_evaluation_id",
            "criterion_index",
            name="uq_criterion_score_eval_index",
        ),
    )
    op.add_column(
        "review_session_employee_evaluations",
        sa.Column("mean_score", sa.Numeric(precision=3, scale=2), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_session_employee_evaluations", "mean_score")
    op.drop_table("review_session_employee_criterion_scores")
    # ### end Alembic commands ###
