"""TalentStatusPeriodLink TalentStatus TalentPeriod

Revision ID: 2c3bc030fab1
Revises: d96aac1c9a1f
Create Date: 2026-05-12 13:14:18.884831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2c3bc030fab1"
down_revision: Union[str, Sequence[str], None] = "d96aac1c9a1f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "talent_periods",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_talent_periods"))
    )
    op.create_table(
        "talent_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=8), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=64), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_talent_statuses")),
        sa.UniqueConstraint("key", name=op.f("uq_talent_statuses_key"))
    )
    op.create_table(
        "talent_status_period_link",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("talent_period_id", sa.Integer(), nullable=False),
        sa.Column("talent_status_id", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
            name=op.f("fk_talent_status_period_link_created_by_employees"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["talent_period_id"],
            ["talent_periods.id"],
            name=op.f(
                "fk_talent_status_period_link_talent_period_id_talent_periods"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["talent_status_id"],
            ["talent_statuses.id"],
            name=op.f(
                "fk_talent_status_period_link_talent_status_id_talent_statuses"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_talent_status_period_link")
        ),
        sa.UniqueConstraint(
            "talent_period_id",
            "talent_status_id",
            name="idx_uq_talent_status_period",
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("talent_status_period_link")
    op.drop_table("talent_statuses")
    op.drop_table("talent_periods")
    # ### end Alembic commands ###
