"""code to empl_event_type not nullable and unique

Revision ID: 64586f81cbd1
Revises: fc204ea8b525
Create Date: 2026-05-23 10:56:26.617136

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "64586f81cbd1"
down_revision: Union[str, Sequence[str], None] = "fc204ea8b525"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employee_event_types",
        "code",
        existing_type=sa.VARCHAR(length=64),
        nullable=False,
    )
    op.create_unique_constraint(
        op.f("uq_employee_event_types_code"), "employee_event_types", ["code"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("uq_employee_event_types_code"),
        "employee_event_types",
        type_="unique",
    )
    op.alter_column(
        "employee_event_types",
        "code",
        existing_type=sa.VARCHAR(length=64),
        nullable=True,
    )
    # ### end Alembic commands ###
