"""add user_settings table and app_settings.user_overridable

Revision ID: 59ebbc025064
Revises: b7f4f891e780
Create Date: 2026-06-30 19:18:39.870241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "59ebbc025064"
down_revision: Union[str, Sequence[str], None] = "b7f4f891e780"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("app_setting_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["app_setting_id"],
            ["app_settings.id"],
            name=op.f("fk_user_settings_app_setting_id_app_settings"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_user_settings_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_settings")),
        sa.UniqueConstraint(
            "employee_id",
            "app_setting_id",
            name="uq_user_setting_employee_app_setting",
        )
    )
    op.create_index(
        op.f("ix_user_settings_app_setting_id"),
        "user_settings",
        ["app_setting_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_settings_employee_id"),
        "user_settings",
        ["employee_id"],
        unique=False,
    )
    op.add_column(
        "app_settings",
        sa.Column(
            "user_overridable",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("app_settings", "user_overridable")
    op.drop_index(
        op.f("ix_user_settings_employee_id"), table_name="user_settings"
    )
    op.drop_index(
        op.f("ix_user_settings_app_setting_id"), table_name="user_settings"
    )
    op.drop_table("user_settings")
    # ### end Alembic commands ###
