"""add is_active to plan_scopes is active not null

Revision ID: 0dead71afd16
Revises: 870107f005a1
Create Date: 2026-06-01 20:52:15.892766

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0dead71afd16"
down_revision: Union[str, Sequence[str], None] = "870107f005a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plan_scopes", "is_active", existing_type=sa.BOOLEAN(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plan_scopes", "is_active", existing_type=sa.BOOLEAN(), nullable=True
    )
    # ### end Alembic commands ###
