"""add training_type_job_links and training_type_job_category_links, drop training_type job/job_category columns

Revision ID: 63eda2ec93fd
Revises: f04b4e050129
Create Date: 2026-07-01 17:07:05.625413

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63eda2ec93fd"
down_revision: Union[str, Sequence[str], None] = "f04b4e050129"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted by hand: ###
    # ### constraint names shortened below 63-char Postgres limit,   ###
    # ### and existing job_id/job_category_id values are carried     ###
    # ### into the new link tables before the columns are dropped.   ###
    op.create_table(
        "training_type_job_category_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("training_type_id", sa.Integer(), nullable=False),
        sa.Column("job_category_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_category_id"],
            ["job_categories.id"],
            name="fk_ttjcl_job_category_id_job_categories",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["training_type_id"],
            ["training_types.id"],
            name="fk_ttjcl_training_type_id_training_types",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_training_type_job_category_links")
        ),
        sa.UniqueConstraint(
            "training_type_id",
            "job_category_id",
            name="uq_training_type_job_category",
        )
    )
    op.create_table(
        "training_type_job_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("training_type_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
            name=op.f("fk_training_type_job_links_job_id_jobs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["training_type_id"],
            ["training_types.id"],
            name="fk_ttjl_training_type_id_training_types",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_type_job_links")),
        sa.UniqueConstraint(
            "training_type_id", "job_id", name="uq_training_type_job"
        )
    )

    # Carry forward any existing single-value job_id / job_category_id data
    # into the new link tables before dropping the columns.
    op.execute(
        """
        INSERT INTO training_type_job_links (training_type_id, job_id, created_at)
        SELECT id, job_id, now() FROM training_types WHERE job_id IS NOT NULL
        """
    )
    op.execute(
        """
        INSERT INTO training_type_job_category_links
            (training_type_id, job_category_id, created_at)
        SELECT id, job_category_id, now() FROM training_types
        WHERE job_category_id IS NOT NULL
        """
    )

    op.drop_constraint(
        op.f("fk_training_types_job_id_jobs"),
        "training_types",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_training_types_job_category_id_job_categories"),
        "training_types",
        type_="foreignkey",
    )
    op.drop_column("training_types", "job_id")
    op.drop_column("training_types", "job_category_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "training_types",
        sa.Column(
            "job_category_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "training_types",
        sa.Column("job_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_training_types_job_category_id_job_categories"),
        "training_types",
        "job_categories",
        ["job_category_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_training_types_job_id_jobs"),
        "training_types",
        "jobs",
        ["job_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.drop_table("training_type_job_links")
    op.drop_table("training_type_job_category_links")
    # ### end Alembic commands ###
