"""add employee mission tables

Revision ID: 5481033843c6
Revises: 982ecf979453
Create Date: 2026-07-21 17:56:27.332508

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5481033843c6"
down_revision: Union[str, Sequence[str], None] = "982ecf979453"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employee_development_visions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_development_visions_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_employee_development_visions")
        ),
        sa.UniqueConstraint(
            "employee_id",
            name=op.f("uq_employee_development_visions_employee_id"),
        )
    )
    op.create_table(
        "employee_missions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("duration_months", sa.Integer(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "duration_months > 0",
            name=op.f("ck_employee_missions_duration_positive"),
        ),
        sa.CheckConstraint(
            "end_date >= start_date",
            name=op.f("ck_employee_missions_end_after_start"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_missions_employee_id_employees"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_missions"))
    )
    op.create_index(
        op.f("ix_employee_missions_employee_id"),
        "employee_missions",
        ["employee_id"],
        unique=False,
    )
    op.create_table(
        "employee_mission_comments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.Column("author_employee_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_employee_id"],
            ["employees.id"],
            name=op.f(
                "fk_employee_mission_comments_author_employee_id_employees"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["employee_missions.id"],
            name=op.f(
                "fk_employee_mission_comments_mission_id_employee_missions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_employee_mission_comments")
        )
    )
    op.create_index(
        op.f("ix_employee_mission_comments_mission_id"),
        "employee_mission_comments",
        ["mission_id"],
        unique=False,
    )
    op.create_table(
        "employee_mission_dimension_links",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.Column("dimension_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["dimension_id"],
            ["review_dimensions.id"],
            name=op.f(
                "fk_employee_mission_dimension_links_dimension_id_review_dimensions"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["employee_missions.id"],
            name=op.f(
                "fk_employee_mission_dimension_links_mission_id_employee_missions"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_employee_mission_dimension_links")
        ),
        sa.UniqueConstraint(
            "mission_id",
            name=op.f("uq_employee_mission_dimension_links_mission_id"),
        )
    )
    op.create_table(
        "employee_mission_kpis",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("mission_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("percent", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "sort_order", sa.Integer(), server_default="0", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "percent >= 0 AND percent <= 100",
            name=op.f("ck_employee_mission_kpis_percent_range"),
        ),
        sa.ForeignKeyConstraint(
            ["mission_id"],
            ["employee_missions.id"],
            name=op.f("fk_employee_mission_kpis_mission_id_employee_missions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_mission_kpis"))
    )
    op.create_index(
        op.f("ix_employee_mission_kpis_mission_id"),
        "employee_mission_kpis",
        ["mission_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_employee_mission_kpis_mission_id"),
        table_name="employee_mission_kpis",
    )
    op.drop_table("employee_mission_kpis")
    op.drop_table("employee_mission_dimension_links")
    op.drop_index(
        op.f("ix_employee_mission_comments_mission_id"),
        table_name="employee_mission_comments",
    )
    op.drop_table("employee_mission_comments")
    op.drop_index(
        op.f("ix_employee_missions_employee_id"),
        table_name="employee_missions",
    )
    op.drop_table("employee_missions")
    op.drop_table("employee_development_visions")
    # ### end Alembic commands ###
