"""operations field alter

Revision ID: d96aac1c9a1f
Revises: bc8d66e6e979
Create Date: 2026-05-12 13:12:42.348467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d96aac1c9a1f"
down_revision: Union[str, Sequence[str], None] = "bc8d66e6e979"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "operations",
        "name",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=128),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "operations",
        "name",
        existing_type=sa.String(length=128),
        type_=sa.VARCHAR(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
