"""add sort_order to department_categories

Revision ID: b9426bc94b77
Revises: b3b2c3e4819b
Create Date: 2026-06-26 16:17:32.220719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b9426bc94b77"
down_revision: Union[str, Sequence[str], None] = "b3b2c3e4819b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "department_categories",
        sa.Column("sort_order", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("department_categories", "sort_order")
    # ### end Alembic commands ###
