"""add education_degrees and employee_educations

Revision ID: 6d40f55444fa
Revises: 71c0f0020bc5
Create Date: 2026-06-12 13:08:20.586173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d40f55444fa"
down_revision: Union[str, Sequence[str], None] = "71c0f0020bc5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "education_degrees",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name_key", sa.String(length=128), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_education_degrees")),
        sa.UniqueConstraint("name_key", name=op.f("uq_education_degrees_name_key")),
    )
    # Seed the three degrees. name_key matches the translation keys loaded into
    # the DB strings (degreeBachelor / degreeSpecialist / degreeMaster).
    op.execute(
        "INSERT INTO education_degrees (name_key, sort_order, is_active) VALUES "
        "('degreeBachelor', 1, true), "
        "('degreeSpecialist', 2, true), "
        "('degreeMaster', 3, true)"
    )
    op.create_table(
        "employee_educations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("institution", sa.String(length=256), nullable=False),
        sa.Column("degree_id", sa.Integer(), nullable=True),
        sa.Column("speciality", sa.String(length=256), nullable=True),
        sa.Column("graduation_year", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["degree_id"],
            ["education_degrees.id"],
            name=op.f("fk_employee_educations_degree_id_education_degrees"),
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_employee_educations_employee_id_employees"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_educations")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("employee_educations")
    op.drop_table("education_degrees")
    # ### end Alembic commands ###
