"""add created_by to department_job_targets

Revision ID: 4a7cb024ffee
Revises: d4169f80d106
Create Date: 2026-07-12 09:41:40.064957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a7cb024ffee"
down_revision: Union[str, Sequence[str], None] = "d4169f80d106"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "department_job_targets",
        sa.Column("created_by", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        op.f("fk_department_job_targets_created_by_employees"),
        "department_job_targets",
        "employees",
        ["created_by"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_department_job_targets_created_by_employees"),
        "department_job_targets",
        type_="foreignkey",
    )
    op.drop_column("department_job_targets", "created_by")
    # ### end Alembic commands ###
