"""queue ordering columns

Revision ID: e6649c6b476c
Revises: 5faf9b08f259
Create Date: 2026-06-20 11:53:58.175807

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e6649c6b476c"
down_revision: Union[str, Sequence[str], None] = "5faf9b08f259"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "process_role_holder_employee_links",
        sa.Column("order_position", sa.Integer(), nullable=True),
    )
    op.add_column(
        "review_session_employees",
        sa.Column("queue_position", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("review_session_employees", "queue_position")
    op.drop_column("process_role_holder_employee_links", "order_position")
    # ### end Alembic commands ###
