"""add tables related to TalentAudit

Revision ID: f035c5d24c0b
Revises: e8a38e952fe6
Create Date: 2026-05-12 13:18:59.157530

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f035c5d24c0b"
down_revision: Union[str, Sequence[str], None] = "e8a38e952fe6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "talent_audit_interview_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_talent_audit_interview_statuses")
        ),
        sa.UniqueConstraint(
            "name", name=op.f("uq_talent_audit_interview_statuses_name")
        )
    )
    op.create_table(
        "talent_audit_job_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint(
            "id", name=op.f("pk_talent_audit_job_statuses")
        ),
        sa.UniqueConstraint(
            "name", name=op.f("uq_talent_audit_job_statuses_name")
        )
    )
    op.create_table(
        "talent_audit_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_talent_audit_statuses")),
        sa.UniqueConstraint(
            "name", name=op.f("uq_talent_audit_statuses_name")
        )
    )
    op.create_table(
        "talent_audit",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
            name=op.f("fk_talent_audit_created_by_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
            name=op.f("fk_talent_audit_employee_id_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["talent_audit_statuses.id"],
            name=op.f("fk_talent_audit_status_id_talent_audit_statuses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_talent_audit")),
        sa.UniqueConstraint(
            "employee_id", name=op.f("uq_talent_audit_employee_id")
        )
    )
    op.create_table(
        "talent_audit_job",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("talent_audit_id", sa.Integer(), nullable=False),
        sa.Column("target_job_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column(
            "talent_status_period_link_id", sa.Integer(), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
            name=op.f("fk_talent_audit_job_created_by_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["talent_audit_job_statuses.id"],
            name=op.f(
                "fk_talent_audit_job_status_id_talent_audit_job_statuses"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["talent_audit_id"],
            ["talent_audit.id"],
            name=op.f("fk_talent_audit_job_talent_audit_id_talent_audit"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["talent_status_period_link_id"],
            ["talent_status_period_link.id"],
            name=op.f(
                "fk_talent_audit_job_talent_status_period_link_id_talent_status_period_link"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["target_job_id"],
            ["jobs.id"],
            name=op.f("fk_talent_audit_job_target_job_id_jobs"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_talent_audit_job"))
    )
    op.create_table(
        "talent_audit_interview",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("talent_audit_job_id", sa.Integer(), nullable=False),
        sa.Column("status_id", sa.Integer(), nullable=False),
        sa.Column("interview_date", sa.Date(), nullable=False),
        sa.Column(
            "talent_status_period_link_id", sa.Integer(), nullable=False
        ),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["employees.id"],
            name=op.f("fk_talent_audit_interview_created_by_employees"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["status_id"],
            ["talent_audit_interview_statuses.id"],
            name=op.f(
                "fk_talent_audit_interview_status_id_talent_audit_interview_statuses"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["talent_audit_job_id"],
            ["talent_audit_job.id"],
            name=op.f(
                "fk_talent_audit_interview_talent_audit_job_id_talent_audit_job"
            ),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["talent_status_period_link_id"],
            ["talent_status_period_link.id"],
            name=op.f(
                "fk_talent_audit_interview_talent_status_period_link_id_talent_status_period_link"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_talent_audit_interview"))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("talent_audit_interview")
    op.drop_table("talent_audit_job")
    op.drop_table("talent_audit")
    op.drop_table("talent_audit_statuses")
    op.drop_table("talent_audit_job_statuses")
    op.drop_table("talent_audit_interview_statuses")
    # ### end Alembic commands ###
