"""add operation and links tables

Revision ID: e181d94c330b
Revises: e3bc408853ac
Create Date: 2026-04-16 16:50:55.609382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e181d94c330b'
down_revision: Union[str, Sequence[str], None] = 'e3bc408853ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),                    
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations')),
    sa.UniqueConstraint('name', name=op.f('uq_operations_name'))
    )
    op.create_table('job_user_group_links',
    sa.Column('id', sa.Integer(), nullable=False),                
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_user_group_links_job_id_jobs')),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_groups.id'], name=op.f('fk_job_user_group_links_user_group_id_user_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_user_group_links')),
    sa.UniqueConstraint('job_id', 'user_group_id', name='idx_uq_job_user_group')
    )
    op.create_table('operation_user_group_links',
    sa.Column('id', sa.Integer(), nullable=False),                
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_operation_user_group_links_operation_id_operations')),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_groups.id'], name=op.f('fk_operation_user_group_links_user_group_id_user_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_user_group_links')),
    sa.UniqueConstraint('operation_id', 'user_group_id', name='idx_uq_operation_user_group')
    )
    op.create_table('user_user_group_links',
    sa.Column('id', sa.Integer(), nullable=False),                
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_group_id'], ['user_groups.id'], name=op.f('fk_user_user_group_links_user_group_id_user_groups')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_user_group_links_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_user_group_links')),
    sa.UniqueConstraint('user_id', 'user_group_id', name='idx_uq_user_user_group')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_user_group_links')
    op.drop_table('operation_user_group_links')
    op.drop_table('job_user_group_links')
    op.drop_table('operations')
    # ### end Alembic commands ###
