"""add user related tables

Revision ID: e3bc408853ac
Revises: 7daf75b09de5
Create Date: 2026-04-16 13:07:53.725397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3bc408853ac'
down_revision: Union[str, Sequence[str], None] = '7daf75b09de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),                
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('name', name=op.f('uq_jobs_name'))
    )

    op.create_table('msg_keys',
    sa.Column('id', sa.Integer(), nullable=False),         
    sa.Column('key_name', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_msg_keys')),
    sa.UniqueConstraint('key_name', name=op.f('uq_msg_keys_key_name'))
    )
    op.create_table('user_group_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_group_types')),
    sa.UniqueConstraint('name', name=op.f('uq_user_group_types_name'))
    )
    op.create_table('msg',
    sa.Column('id', sa.Integer(), nullable=False),    
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('msg_key_id', sa.Integer(), nullable=True),
    sa.Column('lang_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lang_id'], ['langs.id'], name=op.f('fk_msg_lang_id_langs')),
    sa.ForeignKeyConstraint(['msg_key_id'], ['msg_keys.id'], name=op.f('fk_msg_msg_key_id_msg_keys')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_msg')),
    sa.UniqueConstraint('lang_id', 'msg_key_id', name='uq_msg_key_lang')
    )
    op.create_table('user_groups',
    sa.Column('id', sa.Integer(), nullable=False),   
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_protected', sa.Boolean(), nullable=False),
    sa.Column('user_group_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_group_type_id'], ['user_group_types.id'], name=op.f('fk_user_groups_user_group_type_id_user_group_types')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_groups'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),  
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('lang_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_users_job_id_jobs')),
    sa.ForeignKeyConstraint(['lang_id'], ['langs.id'], name=op.f('fk_users_lang_id_langs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('code', name=op.f('uq_users_code')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_groups')
    op.drop_table('msg')
    op.drop_table('user_group_types')
    op.drop_table('msg_keys')
    op.drop_table('jobs')
    # ### end Alembic commands ###
